import type { ComponentPreviewDefinition } from './types';

export const PREVIEW_REGISTRY: Record<string, ComponentPreviewDefinition> = {
  'elastic-sheet': { id: 'elastic-sheet', componentId: 'elastic-sheet', load: () => import('./items/elastic-sheet'), metadata: { type: 'interactive' } },
  'smart-upload': { id: 'smart-upload', componentId: 'smart-upload', load: () => import('./items/smart-upload'), metadata: { type: 'interactive' } },
  'liquid-command-palette': { id: 'liquid-command-palette', componentId: 'liquid-command-palette', load: () => import('./items/liquid-command-palette'), metadata: { type: 'interactive' } },
  'hold-to-confirm': { id: 'hold-to-confirm', componentId: 'hold-to-confirm', load: () => import('./items/hold-to-confirm'), metadata: { type: 'interactive' } },
  'swipe-action-list': { id: 'swipe-action-list', componentId: 'swipe-action-list', load: () => import('./items/swipe-action-list'), metadata: { type: 'interactive' } },
  'interactive-data-card': { id: 'interactive-data-card', componentId: 'interactive-data-card', load: () => import('./items/interactive-data-card'), metadata: { type: 'interactive' } },
  'timeline-scrubber': { id: 'timeline-scrubber', componentId: 'timeline-scrubber', load: () => import('./items/timeline-scrubber'), metadata: { type: 'interactive' } },
  'ai-prompt-composer': { id: 'ai-prompt-composer', componentId: 'ai-prompt-composer', load: () => import('./items/ai-prompt-composer'), metadata: { type: 'interactive' } },
  'dynamic-island': {
    id: 'dynamic-island',
    componentId: 'dynamic-island',
    load: () => import('./items/dynamic-island'),
    metadata: { type: 'interactive' },
  },
  'airport-matrix-clock': {
    id: 'airport-matrix-clock',
    componentId: 'airport-matrix-clock',
    load: () => import('./items/airport-matrix-clock'),
    metadata: { type: 'interactive' },
  },
  'ai-response': {
    id: 'ai-response',
    componentId: 'ai-response',
    load: () => import('./items/ai-response'),
    metadata: { type: 'interactive' },
  },
  'advanced-data-table': {
    id: 'advanced-data-table',
    componentId: 'advanced-data-table',
    load: () => import('./items/advanced-data-table'),
    metadata: { type: 'interactive' },
  },
  'chat': {
    id: 'chat',
    componentId: 'chat',
    load: () => import('./items/chat'),
    metadata: { type: 'interactive' },
  },
  'ai-agent-activity': {
    id: 'ai-agent-activity',
    componentId: 'ai-agent-activity',
    load: () => import('./items/ai-agent-activity'),
    metadata: { type: 'interactive' },
  },
  'interactive-timeline': {
    id: 'interactive-timeline',
    componentId: 'interactive-timeline',
    load: () => import('./items/interactive-timeline'),
    metadata: { type: 'interactive' },
  },
  'smart-comparison': {
    id: 'smart-comparison',
    componentId: 'smart-comparison',
    load: () => import('./items/smart-comparison'),
    metadata: { type: 'interactive' },
  },
  'activity-feed': {
    id: 'activity-feed',
    componentId: 'activity-feed',
    load: () => import('./items/activity-feed'),
    metadata: { type: 'interactive' },
  },
  'metric-hud': {
    id: 'metric-hud',
    componentId: 'metric-hud',
    load: () => import('./items/metric-hud'),
    metadata: { type: 'interactive' },
  },
  'code-snippet-deck': {
    id: 'code-snippet-deck',
    componentId: 'code-snippet-deck',
    load: () => import('./items/code-snippet-deck'),
    metadata: { type: 'interactive' },
  },
  'magnetic-button': {
    id: 'magnetic-button',
    componentId: 'magnetic-button',
    load: () => import('./items/magnetic-button'),
    metadata: { type: 'interactive' },
  },
  'spotlight-card': {
    id: 'spotlight-card',
    componentId: 'spotlight-card',
    load: () => import('./items/spotlight-card'),
    metadata: { type: 'interactive' },
  },
  'cursor-follower': {
    id: 'cursor-follower',
    componentId: 'cursor-follower',
    load: () => import('./items/cursor-follower'),
    metadata: { type: 'interactive' },
  },
  'expandable-search': {
    id: 'expandable-search',
    componentId: 'expandable-search',
    load: () => import('./items/expandable-search'),
    metadata: { type: 'interactive' },
  },
  'animated-tabs': {
    id: 'animated-tabs',
    componentId: 'animated-tabs',
    load: () => import('./items/animated-tabs'),
    metadata: { type: 'interactive' },
  },
  'floating-action-dock': {
    id: 'floating-action-dock',
    componentId: 'floating-action-dock',
    aliases: ["floating-dock"],
    load: () => import('./items/floating-action-dock'),
    metadata: { type: 'interactive' },
  },
  'reveal-card': {
    id: 'reveal-card',
    componentId: 'reveal-card',
    load: () => import('./items/reveal-card'),
    metadata: { type: 'interactive' },
  },
  'smooth-accordion': {
    id: 'smooth-accordion',
    componentId: 'smooth-accordion',
    load: () => import('./items/smooth-accordion'),
    metadata: { type: 'interactive' },
  },
  'notification-stack': {
    id: 'notification-stack',
    componentId: 'notification-stack',
    load: () => import('./items/notification-stack'),
    metadata: { type: 'interactive' },
  },
  'morphing-dialog': {
    id: 'morphing-dialog',
    componentId: 'morphing-dialog',
    load: () => import('./items/morphing-dialog'),
    metadata: { type: 'interactive' },
  },
  'command-menu': {
    id: 'command-menu',
    componentId: 'command-menu',
    load: () => import('./items/command-menu'),
    metadata: { type: 'interactive' },
  },
  'glass-navbar': {
    id: 'glass-navbar',
    componentId: 'glass-navbar',
    load: () => import('./items/glass-navbar'),
    metadata: { type: 'interactive' },
  },
  'button': {
    id: 'button',
    componentId: 'button',
    load: () => import('./items/button'),
    metadata: { type: 'interactive' },
  },

  'form': {
    id: 'form',
    componentId: 'form',
    load: () => import('./items/form'),
    metadata: { type: 'interactive' },
  },
  'login': {
    id: 'login',
    componentId: 'login',
    load: () => import('./items/login'),
    metadata: { type: 'interactive' },
  },
  'sign-up': {
    id: 'sign-up',
    componentId: 'sign-up',
    load: () => import('./items/sign-up'),
    metadata: { type: 'interactive' },
  },
  'faq': {
    id: 'faq',
    componentId: 'faq',
    load: () => import('./items/faq'),
    metadata: { type: 'interactive' },
  },
  'payment-receipt-printer': {
    id: 'payment-receipt-printer',
    componentId: 'payment-receipt-printer',
    load: () => import('./items/payment-receipt-printer'),
    metadata: { type: 'interactive' },
  },
  'dot-field': {
    id: 'dot-field',
    componentId: 'dot-field',
    load: () => import('./items/dot-field'),
    metadata: { type: 'interactive' },
  },
  'particle-delete': {
    id: 'particle-delete',
    componentId: 'particle-delete',
    load: () => import('./items/particle-delete'),
    metadata: { type: 'interactive' },
  },
  'animated-file-upload': {
    id: 'animated-file-upload',
    componentId: 'animated-file-upload',
    load: () => import('./items/animated-file-upload'),
    metadata: { type: 'interactive' },
  },
  'payment-status': {
    id: 'payment-status',
    componentId: 'payment-status',
    load: () => import('./items/payment-status'),
    metadata: { type: 'interactive' },
  },
  'undo-toast': {
    id: 'undo-toast',
    componentId: 'undo-toast',
    load: () => import('./items/undo-toast'),
    metadata: { type: 'interactive' },
  },
  'expandable-data-row': {
    id: 'expandable-data-row',
    componentId: 'expandable-data-row',
    load: () => import('./items/expandable-data-row'),
    metadata: { type: 'interactive' },
  },
  'scroll-progress-nav': {
    id: 'scroll-progress-nav',
    componentId: 'scroll-progress-nav',
    load: () => import('./items/scroll-progress-nav'),
    metadata: { type: 'interactive' },
  },
  'animated-number': {
    id: 'animated-number',
    componentId: 'animated-number',
    load: () => import('./items/animated-number'),
    metadata: { type: 'interactive' },
  },
  'spotlight-search': {
    id: 'spotlight-search',
    componentId: 'spotlight-search',
    load: () => import('./items/spotlight-search'),
    metadata: { type: 'interactive' },
  },
  'morphing-button': {
    id: 'morphing-button',
    componentId: 'morphing-button',
    load: () => import('./items/morphing-button'),
    metadata: { type: 'interactive' },
  },
  'drag-to-confirm': {
    id: 'drag-to-confirm',
    componentId: 'drag-to-confirm',
    load: () => import('./items/drag-to-confirm'),
    metadata: { type: 'interactive' },
  },
  'peek-card': {
    id: 'peek-card',
    componentId: 'peek-card',
    load: () => import('./items/peek-card'),
    metadata: { type: 'interactive' },
  },
  'selection-basket': {
    id: 'selection-basket',
    componentId: 'selection-basket',
    load: () => import('./items/selection-basket'),
    metadata: { type: 'interactive' },
  },
  'focus-mode': {
    id: 'focus-mode',
    componentId: 'focus-mode',
    load: () => import('./items/focus-mode'),
    metadata: { type: 'interactive' },
  },
  'loader': {
    id: 'loader',
    componentId: 'loader',
    load: () => import('./items/loader'),
    metadata: { type: 'interactive' },
  },
  'small-floating-dock': {
    id: 'small-floating-dock',
    componentId: 'small-floating-dock',
    load: () => import('./items/small-floating-dock'),
    metadata: { type: 'interactive' },
  },
  'hamburger-menu': {
    id: 'hamburger-menu',
    componentId: 'hamburger-menu',
    load: () => import('./items/hamburger-menu'),
    metadata: { type: 'interactive' },
  },
  'notification-bell': {
    id: 'notification-bell',
    componentId: 'notification-bell',
    load: () => import('./items/notification-bell'),
    metadata: { type: 'interactive' },
  },
  'ios-search-bar': {
    id: 'ios-search-bar',
    componentId: 'ios-search-bar',
    load: () => import('./items/ios-search-bar'),
    metadata: { type: 'interactive' },
  },
  'typewriter-button': {
    id: 'typewriter-button',
    componentId: 'typewriter-button',
    load: () => import('./items/typewriter-button'),
    metadata: { type: 'interactive' },
  },
  'depth-corridor': {
    id: 'depth-corridor',
    componentId: 'depth-corridor',
    load: () => import('./items/depth-corridor'),
    metadata: { type: 'interactive' },
  },
  'density-lens': {
    id: 'density-lens',
    componentId: 'density-lens',
    load: () => import('./items/density-lens'),
    metadata: { type: 'interactive' },
  },
  'torque-dial': {
    id: 'torque-dial',
    componentId: 'torque-dial',
    load: () => import('./items/torque-dial'),
    metadata: { type: 'interactive' },
  },
  'stack-unfold-panel': {
    id: 'stack-unfold-panel',
    componentId: 'stack-unfold-panel',
    load: () => import('./items/stack-unfold-panel'),
    metadata: { type: 'interactive' },
  },
  'dependency-trace': {
    id: 'dependency-trace',
    componentId: 'dependency-trace',
    load: () => import('./items/dependency-trace'),
    metadata: { type: 'interactive' },
  },
  'batch-gesture-tray': {
    id: 'batch-gesture-tray',
    componentId: 'batch-gesture-tray',
    load: () => import('./items/batch-gesture-tray'),
    metadata: { type: 'interactive' },
  },
  'recovery-ledger': {
    id: 'recovery-ledger',
    componentId: 'recovery-ledger',
    load: () => import('./items/recovery-ledger'),
    metadata: { type: 'interactive' },
  },
  'rocket-party-popper': {
    id: 'rocket-party-popper',
    componentId: 'rocket-party-popper',
    aliases: ["achievement-reveal"],
    load: () => import('./items/rocket-party-popper'),
    metadata: { type: 'interactive' },
  },
  'branching-submenu': {
    id: 'branching-submenu',
    componentId: 'branching-submenu',
    load: () => import('./items/branching-submenu'),
    metadata: { type: 'interactive' },
  },
  'mac-os-folder-cards': {
    id: 'mac-os-folder-cards',
    componentId: 'mac-os-folder-cards',
    aliases: ["macos-folder-cards", "velocity-aware-scroll-cards"],
    load: () => import('./items/mac-os-folder-cards'),
    metadata: { type: 'interactive' },
  },
  'gravity-particle-burst': {
    id: 'gravity-particle-burst',
    componentId: 'gravity-particle-burst',
    load: () => import('./items/gravity-particle-burst'),
    metadata: { type: 'interactive' },
  },
  'liquid-ripple-button': {
    id: 'liquid-ripple-button',
    componentId: 'liquid-ripple-button',
    load: () => import('./items/liquid-ripple-button'),
    metadata: { type: 'interactive' },
  },
  'neon-edge-button': {
    id: 'neon-edge-button',
    componentId: 'neon-edge-button',
    load: () => import('./items/neon-edge-button'),
    metadata: { type: 'interactive' },
  },
  'orbital-loading-ring': {
    id: 'orbital-loading-ring',
    componentId: 'orbital-loading-ring',
    load: () => import('./items/orbital-loading-ring'),
    metadata: { type: 'interactive' },
  },
  'pill-navigation': {
    id: 'pill-navigation',
    componentId: 'pill-navigation',
    load: () => import('./items/pill-navigation'),
    metadata: { type: 'interactive' },
  },
  'text-scramble-decoder': {
    id: 'text-scramble-decoder',
    componentId: 'text-scramble-decoder',
    load: () => import('./items/text-scramble-decoder'),
    metadata: { type: 'interactive' },
  },
  'intro-loader': {
    id: 'intro-loader',
    componentId: 'intro-loader',
    load: () => import('./items/intro-loader'),
    metadata: { type: 'interactive' },
  },
  'nimbu-mirchi': {
    id: 'nimbu-mirchi',
    componentId: 'nimbu-mirchi',
    load: () => import('./items/nimbu-mirchi'),
    metadata: { type: 'interactive' },
  },
  'evil-eye': {
    id: 'evil-eye',
    componentId: 'evil-eye',
    load: () => import('./items/evil-eye'),
    metadata: { type: 'interactive' },
  },
  'wallet-card': {
    id: 'wallet-card',
    componentId: 'wallet-card',
    load: () => import('./items/wallet-card'),
    metadata: { type: 'interactive' },
  },
  'circular-orbit': {
    id: 'circular-orbit',
    componentId: 'circular-orbit',
    load: () => import('./items/circular-orbit'),
    metadata: { type: 'interactive' },
  },
  'profile-card': {
    id: 'profile-card',
    componentId: 'profile-card',
    load: () => import('./items/profile-card'),
    metadata: { type: 'interactive' },
  },
  'book-call-button': {
    id: 'book-call-button',
    componentId: 'book-call-button',
    load: () => import('./items/book-call-button'),
    metadata: { type: 'interactive' },
  },
  'gooey-menu': {
    id: 'gooey-menu',
    componentId: 'gooey-menu',
    load: () => import('./items/gooey-menu'),
    metadata: { type: 'interactive' },
  },
  'morphing-shape-loader': {
    id: 'morphing-shape-loader',
    componentId: 'morphing-shape-loader',
    load: () => import('./items/morphing-shape-loader'),
    metadata: { type: 'interactive' },
  },
  'liquid-toggle': {
    id: 'liquid-toggle',
    componentId: 'liquid-toggle',
    load: () => import('./items/liquid-toggle'),
    metadata: { type: 'interactive' },
  },
  'press-button': {
    id: 'press-button',
    componentId: 'press-button',
    load: () => import('./items/press-button'),
    metadata: { type: 'interactive' },
  },
  'lock-input': {
    id: 'lock-input',
    componentId: 'lock-input',
    load: () => import('./items/lock-input'),
    metadata: { type: 'interactive' },
  },
  'spring-select': {
    id: 'spring-select',
    componentId: 'spring-select',
    load: () => import('./items/spring-select'),
    metadata: { type: 'interactive' },
  },
  'draw-checkbox': {
    id: 'draw-checkbox',
    componentId: 'draw-checkbox',
    load: () => import('./items/draw-checkbox'),
    metadata: { type: 'interactive' },
  },
  'stretch-switch': {
    id: 'stretch-switch',
    componentId: 'stretch-switch',
    load: () => import('./items/stretch-switch'),
    metadata: { type: 'interactive' },
  },
  'settle-modal': {
    id: 'settle-modal',
    componentId: 'settle-modal',
    load: () => import('./items/settle-modal'),
    metadata: { type: 'interactive' },
  },
  'velocity-toast': {
    id: 'velocity-toast',
    componentId: 'velocity-toast',
    load: () => import('./items/velocity-toast'),
    metadata: { type: 'interactive' },
  },
  'directional-tooltip': {
    id: 'directional-tooltip',
    componentId: 'directional-tooltip',
    load: () => import('./items/directional-tooltip'),
    metadata: { type: 'interactive' },
  },
  'origin-dropdown': {
    id: 'origin-dropdown',
    componentId: 'origin-dropdown',
    load: () => import('./items/origin-dropdown'),
    metadata: { type: 'interactive' },
  },
  'unfold-accordion': {
    id: 'unfold-accordion',
    componentId: 'unfold-accordion',
    load: () => import('./items/unfold-accordion'),
    metadata: { type: 'interactive' },
  },
  'slide-pagination': {
    id: 'slide-pagination',
    componentId: 'slide-pagination',
    load: () => import('./items/slide-pagination'),
    metadata: { type: 'interactive' },
  },
  'pricing': {
    id: 'pricing',
    componentId: 'pricing',
    load: () => import('./items/pricing'),
    metadata: { type: 'interactive' },
  },
  'morphing-blob': {
    id: 'morphing-blob',
    componentId: 'morphing-blob',
    load: () => import('./items/morphing-blob'),
    metadata: { type: 'interactive' },
  },
  'otp-input': {
    id: 'otp-input',
    componentId: 'otp-input',
    load: () => import('./items/otp-input'),
    metadata: { type: 'interactive' },
  },
  'thinking-orb': {
    id: 'thinking-orb',
    componentId: 'thinking-orb',
    load: () => import('./items/thinking-orb'),
    metadata: { type: 'interactive' },
  },
  'car-smoke-page-transition': {
    id: 'car-smoke-page-transition',
    componentId: 'car-smoke-page-transition',
    load: () => import('./items/car-smoke-page-transition'),
    metadata: { type: 'interactive' },
  },
  'stacked-cards': {
    id: 'stacked-cards',
    componentId: 'stacked-cards',
    aliases: ["stacked-card", "stack-cards", "stack-card"],
    load: () => import('./items/stacked-cards'),
    metadata: { type: 'interactive' },
  },
  'story-card': {
    id: 'story-card',
    componentId: 'story-card',
    aliases: ["story-cards"],
    load: () => import('./items/story-card'),
    metadata: { type: 'interactive' },
  },
  'avatar-stack': {
    id: 'avatar-stack',
    componentId: 'avatar-stack',
    aliases: ["avatar-stacks", "avatarstack"],
    load: () => import('./items/avatar-stack'),
    metadata: { type: 'interactive' },
  },
  'glyph-matrix': {
    id: 'glyph-matrix',
    componentId: 'glyph-matrix',
    aliases: ["glyph-matrices", "glyphmatrix"],
    load: () => import('./items/glyph-matrix'),
    metadata: { type: 'interactive' },
  },
  'morphing-icon': {
    id: 'morphing-icon',
    componentId: 'morphing-icon',
    aliases: ["morphing-icons", "morphingicon"],
    load: () => import('./items/morphing-icon'),
    metadata: { type: 'interactive' },
  },
  'speed-warp': {
    id: 'speed-warp',
    componentId: 'speed-warp',
    aliases: ["speed-warps", "speedwarp"],
    load: () => import('./items/speed-warp'),
    metadata: { type: 'interactive' },
  },
  'split-button': {
    id: 'split-button',
    componentId: 'split-button',
    aliases: ["split-buttons", "splitbutton"],
    load: () => import('./items/split-button'),
    metadata: { type: 'interactive' },
  },
  'dot-shader': {
    id: 'dot-shader',
    componentId: 'dot-shader',
    aliases: ["dotshader", "dot-matrix-shader"],
    load: () => import('./items/dot-shader'),
    metadata: { type: 'interactive' },
  },
  'glitch-text': {
    id: 'glitch-text',
    componentId: 'glitch-text',
    aliases: ["glitchtext", "glitch-typography"],
    load: () => import('./items/glitch-text'),
    metadata: { type: 'interactive' },
  },
  'meteors': {
    id: 'meteors',
    componentId: 'meteors',
    aliases: ["meteor-shower", "meteor-card"],
    load: () => import('./items/meteors'),
    metadata: { type: 'interactive' },
  },
  'rainbow-button': {
    id: 'rainbow-button',
    componentId: 'rainbow-button',
    aliases: ["rainbowbutton", "chromatic-button"],
    load: () => import('./items/rainbow-button'),
    metadata: { type: 'interactive' },
  },
  'scrollvelocitytext': {
    id: 'scrollvelocitytext',
    componentId: 'scrollvelocitytext',
    aliases: ["scroll-velocity-text", "velocity-text"],
    load: () => import('./items/scrollvelocitytext'),
    metadata: { type: 'interactive' },
  },
  'shooting-stars': {
    id: 'shooting-stars',
    componentId: 'shooting-stars',
    aliases: ["shootingstars", "celestial-stars"],
    load: () => import('./items/shooting-stars'),
    metadata: { type: 'interactive' },
  },
  'sparkles-core': {
    id: 'sparkles-core',
    componentId: 'sparkles-core',
    aliases: ["sparklescore", "sparkles"],
    load: () => import('./items/sparkles-core'),
    metadata: { type: 'interactive' },
  },
  'sticky-pages': {
    id: 'sticky-pages',
    componentId: 'sticky-pages',
    aliases: ["stickypages", "sticky-stacking-pages"],
    load: () => import('./items/sticky-pages'),
    metadata: { type: 'interactive' },
  },
  'not-found': {
    id: 'not-found',
    componentId: 'not-found',
    aliases: ['404', 'notfound', 'error-404'],
    load: () => import('./items/not-found'),
    metadata: { type: 'interactive' },
  },
  'pull-to-refresh': {
    id: 'pull-to-refresh',
    componentId: 'pull-to-refresh',
    aliases: ['pulltorefresh', 'pull-refresh'],
    load: () => import('./items/pull-to-refresh'),
    metadata: { type: 'interactive' },
  },
};

// Fast lookup map supporting both primary slugs and aliases
const ALIAS_MAP = new Map<string, string>();
for (const [id, def] of Object.entries(PREVIEW_REGISTRY)) {
  ALIAS_MAP.set(id, id);
  if (def.aliases) {
    for (const alias of def.aliases) {
      ALIAS_MAP.set(alias, id);
    }
  }
}

export function getComponentPreview(idOrSlug: string): ComponentPreviewDefinition | undefined {
  const targetId = ALIAS_MAP.get(idOrSlug) || idOrSlug;
  return PREVIEW_REGISTRY[targetId];
}
