import { Component, ElementRef, ViewEncapsulation, contentChild, forwardRef, inject, input, output, signal, viewChild } from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';
import { installDataTableMotion } from './data-table-motion';
import { KittuDataTableController } from './data-table-controller';
/*
ISC License

Copyright (c) 2026 Lucide Icons and Contributors

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

---

The following Lucide icons are derived from the Feather project:

airplay, alert-circle, alert-octagon, alert-triangle, aperture, arrow-down-circle, arrow-down-left, arrow-down-right, arrow-down, arrow-left-circle, arrow-left, arrow-right-circle, arrow-right, arrow-up-circle, arrow-up-left, arrow-up-right, arrow-up, at-sign, calendar, cast, check, chevron-down, chevron-left, chevron-right, chevron-up, chevrons-down, chevrons-left, chevrons-right, chevrons-up, circle, clipboard, clock, code, columns, command, compass, corner-down-left, corner-down-right, corner-left-down, corner-left-up, corner-right-down, corner-right-up, corner-up-left, corner-up-right, crosshair, database, divide-circle, divide-square, dollar-sign, download, external-link, feather, frown, hash, headphones, help-circle, info, italic, key, layout, life-buoy, link-2, link, loader, lock, log-in, log-out, maximize, meh, minimize, minimize-2, minus-circle, minus-square, minus, monitor, moon, more-horizontal, more-vertical, move, music, navigation-2, navigation, octagon, pause-circle, percent, plus-circle, plus-square, plus, power, radio, rss, search, server, share, shopping-bag, sidebar, smartphone, smile, square, table-2, tablet, target, terminal, trash-2, trash, triangle, tv, type, upload, x-circle, x-octagon, x-square, x, zoom-in, zoom-out

The MIT License (MIT) (for the icons listed above)

Copyright (c) 2013-present Cole Bemis

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

*/

@Component({selector:'kittu-data-table-toolbar',standalone:true,imports:[NgTemplateOutlet],host:{style:'display:contents'},template:`<div [class]="'k-dt-toolbar '+className()">
<div class="k-dt-toolbar-row"><div class="k-dt-title">@if(title()){<h3>{{title()}}</h3>}@if(table.selectedRowIds().size){<span class="k-dt-selected-count"><i></i>{{table.selectedRowIds().size}} selected</span>}</div>
<div class="k-dt-controls"><div class="k-dt-search"><svg class="k-dt-icon " viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m21 21-4.34-4.34"/><circle cx="11" cy="11" r="8"/></svg><input type="text" aria-label="Search records" [placeholder]="searchPlaceholder()" [value]="table.searchTerm()" (input)="table.searchTerm.set($any($event.target).value)"/>@if(table.searchTerm()){<button type="button" aria-label="Clear search" (click)="table.searchTerm.set('')"><svg class="k-dt-icon " viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg></button>}</div>
<button type="button" class="k-dt-control" aria-label="Toggle view mode" [attr.title]="table.viewMode()==='cards'?'Switch to Table view':'Switch to Cards view'" (click)="table.viewMode.set(table.viewMode()==='cards'?'table':'cards')">@if(table.viewMode()==='cards'){<svg class="k-dt-icon " viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 5h.01"/><path d="M3 12h.01"/><path d="M3 19h.01"/><path d="M8 5h13"/><path d="M8 12h13"/><path d="M8 19h13"/></svg>}@else{<svg class="k-dt-icon " viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect width="7" height="7" x="3" y="3" rx="1"/><rect width="7" height="7" x="14" y="3" rx="1"/><rect width="7" height="7" x="14" y="14" rx="1"/><rect width="7" height="7" x="3" y="14" rx="1"/></svg>}</button>
<div class="k-dt-picker-wrap" (keydown.escape)="closePicker()"><button #pickerButton type="button" class="k-dt-control" title="Toggle columns" aria-label="Toggle visible columns" [attr.aria-expanded]="pickerOpen()" (click)="pickerOpen.set(!pickerOpen())"><svg class="k-dt-icon " viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M10 5H3"/><path d="M12 19H3"/><path d="M14 3v4"/><path d="M16 17v4"/><path d="M21 12h-9"/><path d="M21 19h-5"/><path d="M21 5h-7"/><path d="M8 10v4"/><path d="M8 12H3"/></svg></button>@if(pickerOpen()){<div class="k-dt-picker"><div>Columns</div>@for(col of table.columns();track col.id){<label><input type="checkbox" [checked]="!table.hiddenColumnIds().has(col.id)" (change)="table.toggleColumnVisibility(col.id)"/><span>{{col.header}}</span></label>}</div>}</div></div></div>
@if(table.selectedRowIds().size){<div class="k-dt-bulk"><span>{{table.selectedRowIds().size}} item{{table.selectedRowIds().size===1?'':'s'}} selected:</span><div>@if(onBulkExport()){<button type="button" (click)="exportSelected()"><svg class="k-dt-icon " viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 15V3"/><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><path d="m7 10 5 5 5-5"/></svg>Export</button>}@if(onBulkDelete()){<button type="button" class="k-dt-delete" (click)="deleteSelected()"><svg class="k-dt-icon " viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M10 11v6"/><path d="M14 11v6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"/><path d="M3 6h18"/><path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg>Delete</button>}</div></div>}</div>`})
export class KittuDataTableToolbarComponent {readonly table=inject(KittuDataTableController);readonly className=input('');readonly title=input('');readonly searchPlaceholder=input('Search...');readonly onBulkDelete=input<(ids:string[])=>void>();readonly onBulkExport=input<(ids:string[])=>void>();readonly bulkDelete=output<string[]>();readonly bulkExport=output<string[]>();readonly pickerOpen=signal(false);readonly pickerButton=viewChild<ElementRef<HTMLButtonElement>>('pickerButton');closePicker():void{this.pickerOpen.set(false);this.pickerButton()?.nativeElement.focus();}deleteSelected():void{const ids=[...this.table.selectedRowIds()];this.onBulkDelete()?.(ids);this.bulkDelete.emit(ids);}exportSelected():void{const ids=[...this.table.selectedRowIds()];this.onBulkExport()?.(ids);this.bulkExport.emit(ids);}}

@Component({selector:'kittu-data-table-filters',standalone:true,imports:[NgTemplateOutlet],host:{style:'display:contents'},template:`@if(table.filterableColumns().length){<div [class]="'k-dt-filters '+className()"><span>Filters:</span>@for(col of table.filterableColumns();track col.id){<div class="k-dt-filter-group"><span>{{col.header}}:</span>@for(option of col.filterOptions;track option.value){<button type="button" [attr.aria-pressed]="table.activeFilters()[col.id]?.includes(option.value)||false" [class.k-dt-active-filter]="table.activeFilters()[col.id]?.includes(option.value)" (click)="table.toggleFilter(col.id,option.value)">{{option.label}}</button>}</div>}@if(table.activeCount()){<button type="button" class="k-dt-reset" (click)="table.clearFilters()">Reset ({{table.activeCount()}})</button>}</div>}`})
export class KittuDataTableFiltersComponent {readonly table=inject(KittuDataTableController);readonly className=input('');}

@Component({selector:'kittu-data-table-content',standalone:true,imports:[NgTemplateOutlet],host:{style:'display:contents'},template:`@if(table.error()){<div class="k-dt-state" role="alert"><svg class="k-dt-icon " viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"/><line x1="12" x2="12" y1="8" y2="12"/><line x1="12" x2="12.01" y1="16" y2="16"/></svg><p class="k-dt-error-title">Failed to load data</p><p>{{table.error()}}</p></div>}@else if(table.isLoading()){<div class="k-dt-loading" role="status" aria-label="Loading records">@for(i of [1,2,3,4,5];track i){<div></div>}</div>}@else if(!table.paginatedData().length){<div class="k-dt-state k-dt-empty"><div class="k-dt-empty-icon"><svg class="k-dt-icon " viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m21 21-4.34-4.34"/><circle cx="11" cy="11" r="8"/></svg></div><h4>{{emptyTitle()}}</h4><p>{{emptyDescription()}}</p><button type="button" (click)="table.clearFilters()">Clear filters</button></div>}@else if(table.viewMode()==='cards'){
<div [class]="'k-dt-cards '+className()">@for(row of table.paginatedData();track table.getRowId()(row,$index);let index=$index){@let id=table.getRowId()(row,index);@let primary=table.visibleColumns()[0];<div class="k-dt-card" [class.k-dt-card-selected]="table.selectedRowIds().has(id)"><div class="k-dt-card-heading"><div><input type="checkbox" [checked]="table.selectedRowIds().has(id)" [attr.aria-label]="'Select row '+id" (change)="table.toggleRowSelection(id)"/><span>@if(primary){@if(primary.cell){<ng-container *ngTemplateOutlet="primary.cell!;context:{$implicit:row,row:row,value:table.value(row,primary)}"/>}@else{ {{table.value(row,primary)??''}} }}</span></div>@if(table.renderSubComponent()){<button type="button" class="k-dt-expand" [attr.aria-expanded]="table.expandedRowIds().has(id)" [attr.aria-label]="table.expandedRowIds().has(id)?'Collapse row details':'Expand row details'" (click)="table.toggleRowExpansion(id)"><span [class.k-dt-rotated]="table.expandedRowIds().has(id)"><svg class="k-dt-icon " viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m9 18 6-6-6-6"/></svg></span></button>}</div>
@if(table.visibleColumns().length>1){<div class="k-dt-card-grid">@for(col of table.visibleColumns().slice(1);track col.id){<div><span>{{col.header}}</span><div>@if(col.cell){<ng-container *ngTemplateOutlet="col.cell!;context:{$implicit:row,row:row,value:table.value(row,col)}"/>}@else{ {{table.value(row,col)??'—'}} }</div></div>}</div>}
@if(table.renderSubComponent()&&table.expandedRowIds().has(id)){<div class="k-dt-card-detail"><ng-container *ngTemplateOutlet="table.renderSubComponent()!;context:{$implicit:row,row:row}"/></div>}</div>}</div>
}@else{<div [class]="'k-dt-scroll '+className()"><table><thead><tr><th class="k-dt-select"><input type="checkbox" aria-label="Select all rows" [checked]="table.isAllSelected()" [indeterminate]="table.isIndeterminate()" (change)="table.toggleSelectAll()"/></th>@if(table.renderSubComponent()){<th class="k-dt-expand-cell"></th>}@for(col of table.visibleColumns();track col.id){<th [style.width]="col.width" [style.text-align]="col.align" [attr.aria-sort]="table.sortColumn()===col.id?(table.sortDirection()==='asc'?'ascending':'descending'):'none'">@if(col.sortable){<button type="button" (click)="table.handleSort(col.id)">{{col.header}}@if(table.sortColumn()===col.id){@if(table.sortDirection()==='asc'){<svg class="k-dt-icon " viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m18 15-6-6-6 6"/></svg>}@else{<svg class="k-dt-icon " viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg>}}@else{<svg class="k-dt-icon k-dt-unsorted" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m7 15 5 5 5-5"/><path d="m7 9 5-5 5 5"/></svg>}</button>}@else{ {{col.header}} }</th>}</tr></thead>
<tbody>@for(row of table.paginatedData();track table.getRowId()(row,$index);let index=$index){@let id=table.getRowId()(row,index);<tr [class.k-dt-row-selected]="table.selectedRowIds().has(id)"><td class="k-dt-select"><input type="checkbox" [checked]="table.selectedRowIds().has(id)" [attr.aria-label]="'Select row '+id" (change)="table.toggleRowSelection(id)"/></td>@if(table.renderSubComponent()){<td class="k-dt-expand-cell"><button type="button" class="k-dt-expand" [attr.aria-expanded]="table.expandedRowIds().has(id)" [attr.aria-label]="table.expandedRowIds().has(id)?'Collapse row details':'Expand row details'" (click)="table.toggleRowExpansion(id)"><span [class.k-dt-rotated]="table.expandedRowIds().has(id)"><svg class="k-dt-icon " viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m9 18 6-6-6-6"/></svg></span></button></td>}@for(col of table.visibleColumns();track col.id){<td [style.text-align]="col.align" [class.k-dt-numeric]="col.align==='right'">@if(col.cell){<ng-container *ngTemplateOutlet="col.cell!;context:{$implicit:row,row:row,value:table.value(row,col)}"/>}@else{ {{table.value(row,col)??''}} }</td>}</tr>@if(table.renderSubComponent()&&table.expandedRowIds().has(id)){<tr class="k-dt-detail-row"><td [attr.colspan]="table.visibleColumns().length+2"><div class="k-dt-detail"><ng-container *ngTemplateOutlet="table.renderSubComponent()!;context:{$implicit:row,row:row}"/></div></td></tr>}}</tbody></table></div>}`})
export class KittuDataTableContentComponent {readonly table=inject(KittuDataTableController);readonly className=input('');readonly emptyTitle=input('No matching records found');readonly emptyDescription=input('Try adjusting your search criteria or filters to locate what you are looking for.');}

@Component({selector:'kittu-data-table-pagination',standalone:true,imports:[NgTemplateOutlet],host:{style:'display:contents'},template:`<div [class]="'k-dt-pagination '+className()"><div>Showing <strong>{{table.totalFilteredCount()===0?0:(table.currentPage()-1)*table.pageSize()+1}}–{{endRecord()}}</strong> of <strong>{{table.totalFilteredCount()}}</strong> records</div><div class="k-dt-page-controls"><div class="k-dt-size"><span>Rows per page:</span><select aria-label="Rows per page" [value]="table.pageSize()" (change)="table.pageSize.set(+$any($event.target).value);table.currentPage.set(1)">@for(size of pageSizeOptions();track size){<option [value]="size">{{size}}</option>}</select></div><div class="k-dt-navigation"><button type="button" aria-label="First page" [disabled]="table.currentPage()<=1" (click)="table.currentPage.set(1)"><svg class="k-dt-icon " viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m11 17-5-5 5-5"/><path d="m18 17-5-5 5-5"/></svg></button><button type="button" aria-label="Previous page" [disabled]="table.currentPage()<=1" (click)="table.currentPage.set(table.currentPage()-1)"><svg class="k-dt-icon " viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m15 18-6-6 6-6"/></svg></button><span>{{table.currentPage()}}/{{table.totalPages()||1}}</span><button type="button" aria-label="Next page" [disabled]="table.currentPage()>=table.totalPages()" (click)="table.currentPage.set(table.currentPage()+1)"><svg class="k-dt-icon " viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m9 18 6-6-6-6"/></svg></button><button type="button" aria-label="Last page" [disabled]="table.currentPage()>=table.totalPages()" (click)="table.currentPage.set(table.totalPages())"><svg class="k-dt-icon " viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m6 17 5-5-5-5"/><path d="m13 17 5-5-5-5"/></svg></button></div></div></div>`})
export class KittuDataTablePaginationComponent {readonly table=inject(KittuDataTableController);readonly className=input('');readonly pageSizeOptions=input<number[]>([5,10,20,50]);endRecord():number{return Math.min(this.table.currentPage()*this.table.pageSize(),this.table.totalFilteredCount());}}

@Component({
 selector:'kittu-data-table',standalone:true,
 imports:[KittuDataTableToolbarComponent,KittuDataTableFiltersComponent,KittuDataTableContentComponent,KittuDataTablePaginationComponent],
 providers:[{provide:KittuDataTableController,useExisting:forwardRef(()=>KittuDataTableComponent)}],
 host:{style:'display:block;min-width:0'},encapsulation:ViewEncapsulation.None,styleUrls:['./data-table.css'],
 template:`<div [class]="'k-data-table '+className()" [style.--accent-custom]="accentColor()"><ng-content/>@if(!toolbar()&&!filters()&&!content()&&!pagination()){<kittu-data-table-toolbar/><kittu-data-table-filters/><kittu-data-table-content/><kittu-data-table-pagination/>}</div>`
})
export class KittuDataTableComponent<T = any> extends KittuDataTableController<T> {
 constructor(){super();installDataTableMotion();}
 readonly toolbar=contentChild(KittuDataTableToolbarComponent);readonly filters=contentChild(KittuDataTableFiltersComponent);readonly content=contentChild(KittuDataTableContentComponent);readonly pagination=contentChild(KittuDataTablePaginationComponent);
}
