type Axis={value:number;velocity:number;target:number;delta:number;speed:number;k:number;d:number;m:number;pending:boolean;created:number};
const axis=(k:number,d:number,m:number,value=0):Axis=>({value,velocity:0,target:value,delta:.005,speed:.01,k,d,m,pending:false,created:0});
function target(a:Axis,value:number){a.target=value;a.pending=true;a.created=performance.now();const granular=Math.abs(value-a.value)<5;a.delta=granular?.005:.5;a.speed=granular?.01:2;}
function step(a:Axis,t:number,time:number):boolean{if(a.pending){a.pending=false;const delay=time-a.created;t=delay>40?0:Math.max(0,delay/1000);}const root=Math.sqrt(a.d*a.d-4*a.m*a.k),r1=(-a.d+root)/(2*a.m),r2=(-a.d-root)/(2*a.m),x=a.value-a.target,c1=(a.velocity-r2*x)/(r1-r2),c2=x-c1;a.value=a.target+c1*Math.exp(r1*t)+c2*Math.exp(r2*t);a.velocity=r1*c1*Math.exp(r1*t)+r2*c2*Math.exp(r2*t);const done=Math.abs(a.value-a.target)<=a.delta&&Math.abs(a.velocity)<=a.speed;if(done){a.value=a.target;a.velocity=0;}return done;}
/** AnimatePresence sync: retain exiting content and reverse its sampled spring on reopen. */
export class AccordionMotion{
 private height=axis(170,26,.9);private opacity=axis(170,26,.9);private rotation=axis(380,30,.5);private desired=false;private initialized=false;private activePanel=false;private closing=false;private frame:number|ReturnType<typeof setTimeout>|undefined;private last=0;private destroyed=false;private awaiting=false;private opacityAnimation:Animation|undefined;private opacityOrigin:Axis|undefined;private opacityStart=0;
 constructor(private host:HTMLElement,private remove:()=>void){}
 initialize(open:boolean){this.desired=open;this.initialized=true;this.opacity.value=open?1:0;this.opacity.target=this.opacity.value;target(this.rotation,open?180:0);this.awaiting=true;}
 toggle(open:boolean){this.desired=open;this.awaiting=true;this.retarget(this.rotation,open?180:0);if(!open&&this.activePanel){this.closing=true;const panel=this.host.querySelector<HTMLElement>('.k-sa-panel');if(panel?.style.height==='auto'){this.height.value=panel.getBoundingClientRect().height;this.height.target=this.height.value;this.height.velocity=0;}this.retarget(this.height,0);this.targetOpacity(0);}this.start();}
 rendered(open:boolean){if(this.destroyed)return;const panel=this.host.querySelector<HTMLElement>('.k-sa-panel'),inner=panel?.firstElementChild as HTMLElement|undefined;
  if(panel&&inner&&!this.activePanel){this.activePanel=true;const size=inner.getBoundingClientRect().height;if(this.initialized&&this.awaiting&&this.height.target===0&&this.opacity.value===1){this.height.value=size;this.height.target=size;panel.style.height='auto';panel.style.opacity='1';}else{this.height.value=0;this.height.velocity=0;this.opacity.value=0;this.opacity.velocity=0;target(this.height,size);this.targetOpacity(1);panel.style.height='0px';panel.style.opacity='0';}this.start();}
  if(this.awaiting){this.awaiting=false;if(open&&panel&&inner){this.closing=false;this.retarget(this.height,inner.getBoundingClientRect().height);this.targetOpacity(1);}this.start();}
 }
 private retarget(value:Axis,next:number){const now=performance.now();if(!value.pending&&this.frame!==undefined){const elapsed=Math.max(0,(now-this.last)/1000),previous=value.value;step(value,elapsed,now);value.velocity=elapsed?(value.value-previous)/Math.min(elapsed,.03):0;}target(value,next);}
 private targetOpacity(value:number){if(this.opacityAnimation&&this.opacityOrigin){const now=performance.now(),sampleTime=Math.max(10,now-this.opacityStart),delta=Math.min(10,sampleTime-10),current={...this.opacityOrigin},previous={...this.opacityOrigin};step(current,sampleTime/1000,now);step(previous,(sampleTime-delta)/1000,now);this.opacity.value=current.value;this.opacity.velocity=delta?(current.value-previous.value)/(delta/1000):0;const panel=this.host.querySelector<HTMLElement>('.k-sa-panel');if(panel)panel.style.opacity=String(current.value);this.opacityAnimation.cancel();this.opacityAnimation=undefined;}target(this.opacity,value);}
 private animateOpacity(panel:HTMLElement,time:number){if(typeof panel.animate!=='function'||this.opacity.value===this.opacity.target&&this.opacity.velocity===0)return;const sample={...this.opacity,pending:false},frames:Keyframe[]=[{opacity:sample.value}],times=[0];this.opacityOrigin={...sample};this.opacityStart=time-this.opacity.created>40?time:this.opacity.created;for(let t=10;t<=2000;t+=10){const done=step(sample,.01,time+t);frames.push({opacity:sample.value});times.push(t);if(done)break;}const duration=times.at(-1)!;frames.forEach((frame,index)=>frame.offset=times[index]/duration);this.opacityAnimation=panel.animate(frames,{duration,fill:'forwards',easing:'linear'});this.opacityAnimation.currentTime=time-this.opacity.created>40?0:Math.max(0,time-this.opacity.created);}
 private schedule(){return typeof requestAnimationFrame==='function'?requestAnimationFrame(this.tick):setTimeout(()=>this.tick(performance.now()),16);}
 private start(){if(this.frame===undefined&&!this.destroyed){this.last=performance.now();this.frame=this.schedule();}}
 private tick=(time:number)=>{this.frame=undefined;if(this.destroyed)return;const dt=Math.max(0,(time-this.last)/1000);this.last=time;const panel=this.host.querySelector<HTMLElement>('.k-sa-panel'),chevron=this.host.querySelector<HTMLElement>('.k-sa-chevron');if(this.opacity.pending&&panel)this.animateOpacity(panel,time);const h=step(this.height,dt,time),o=step(this.opacity,dt,time),r=step(this.rotation,dt,time);if(chevron)chevron.style.transform=`rotate(${this.rotation.value}deg)`;if(panel){panel.style.height=h&&this.desired?'auto':Math.max(0,this.height.value)+'px';if(!this.opacityAnimation||o){this.opacityAnimation?.cancel();this.opacityAnimation=undefined;panel.style.opacity=String(this.opacity.value);}}
  if(h&&o&&this.closing){this.closing=false;this.activePanel=false;this.remove();}if(!h||!o||!r)this.frame=this.schedule();
 };
 destroy(){this.destroyed=true;this.opacityAnimation?.cancel();if(this.frame!==undefined){if(typeof cancelAnimationFrame==='function')cancelAnimationFrame(this.frame as number);else clearTimeout(this.frame as ReturnType<typeof setTimeout>);}}
}
