import {DestroyRef,ElementRef,effect,inject,untracked,type Signal,type WritableSignal} from '@angular/core';
import type {TypewriterButtonCallback} from './typewriter-button-types';
interface TypewriterState{text:Signal<string>;charDuration:Signal<number>;autoStart:Signal<boolean>;soundEnabled:Signal<boolean>;soundVolume:Signal<number>;disabled:Signal<boolean>;onComplete:Signal<TypewriterButtonCallback|undefined>;onClick:Signal<TypewriterButtonCallback|undefined>;displayedText:WritableSignal<string>;isTyping:WritableSignal<boolean>}
/** Preserve React's initial-label and dependency-cleanup behavior, including interrupted typing. */
export function installTypewriterButton(state:TypewriterState):void{
 const host=inject<ElementRef<HTMLElement>>(ElementRef).nativeElement;let timeout:ReturnType<typeof setTimeout>|undefined,typing=false,initialized=false,hovered=false,pressed=false,keyPressed=false,activePointer:number|undefined,animation:Animation|undefined;
 const audio=new Map<AudioContext,ReturnType<typeof setTimeout>>();const node=()=>host.tagName==='BUTTON'?host:host.querySelector('button');
 const motion=()=>{const button=node();if(!button||typeof button.animate!=='function')return;const enabled=!typing&&!state.disabled();const scale=enabled?(pressed?.97:hovered?1.02:1):1,y=enabled&&hovered?-1:0;const matrix=new DOMMatrixReadOnly(getComputedStyle(button).transform==='none'?undefined:getComputedStyle(button).transform);animation?.cancel();const r1=(-30+Math.sqrt(140))/(1),r2=(-30-Math.sqrt(140))/(1);const frames=Array.from({length:61},(_,i)=>{const t=i/120,p=1-(r2*Math.exp(r1*t)-r1*Math.exp(r2*t))/(r2-r1);return{transform:`translateY(${matrix.f+(y-matrix.f)*p}px) scale(${matrix.a+(scale-matrix.a)*p})`,offset:i/60};});frames[60].transform=`translateY(${y}px) scale(${scale})`;animation=button.animate(frames,{duration:500,fill:'forwards'});};
 const close=(ctx:AudioContext)=>{try{void ctx.close().catch(()=>{});}catch{/* Unsupported or blocked audio never interrupts typing. */}};
 const play=(volume:number)=>{let ctx:AudioContext|undefined;try{const AudioCtx=window.AudioContext||(window as unknown as {webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!AudioCtx)return;ctx=new AudioCtx();const bufferSize=ctx.sampleRate*.03,buffer=ctx.createBuffer(1,bufferSize,ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<bufferSize;i++)data[i]=(Math.random()*2-1)*Math.exp(-i/(bufferSize*.2));const noise=ctx.createBufferSource();noise.buffer=buffer;const filter=ctx.createBiquadFilter();filter.type='bandpass';filter.frequency.value=1800;filter.Q.value=3;const gain=ctx.createGain();gain.gain.setValueAtTime(volume*.4,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.03);noise.connect(filter);filter.connect(gain);gain.connect(ctx.destination);noise.start();const current=ctx;audio.set(current,setTimeout(()=>{audio.delete(current);close(current);},60));}catch{if(ctx)close(ctx);}};
 const start=()=>{if(typing||state.disabled())return;if(timeout)clearTimeout(timeout);typing=true;state.isTyping.set(true);state.displayedText.set('');motion();const fullText=String(state.text()),duration=state.charDuration(),sound=state.soundEnabled(),volume=state.soundVolume(),complete=state.onComplete();let index=1;const next=()=>{if(index<=fullText.length){state.displayedText.set(fullText.slice(0,index));if(sound)play(volume);index++;timeout=setTimeout(next,duration);}else{typing=false;state.isTyping.set(false);motion();complete?.();}};timeout=setTimeout(next,30);};
 effect(onCleanup=>{const text=state.text(),auto=state.autoStart();state.charDuration();state.soundEnabled();state.soundVolume();state.disabled();state.onComplete();untracked(()=>{if(!initialized){initialized=true;state.displayedText.set(auto?'':text);}if(auto)start();motion();});onCleanup(()=>{if(timeout)clearTimeout(timeout);});});
 const click=(event:Event)=>{if(typing){event.stopImmediatePropagation();return;}if(state.disabled())return;start();state.onClick()?.();};
 const enter=(event:Event)=>{if(event instanceof PointerEvent&&event.pointerType==='touch')return;hovered=true;motion();},leave=()=>{hovered=false;motion();},down=(event:Event)=>{if(event instanceof PointerEvent){if(event.button!==0||!event.isPrimary)return;activePointer=event.pointerId;}pressed=true;motion();},up=(event:Event)=>{if(event instanceof PointerEvent&&activePointer!==undefined&&event.pointerId!==activePointer)return;activePointer=undefined;pressed=false;motion();};
 const keydown=(event:Event)=>{const key=event as KeyboardEvent;if(key.key==='Enter'&&!key.repeat&&!state.disabled()){keyPressed=true;pressed=true;motion();}};const keyup=(event:Event)=>{if((event as KeyboardEvent).key==='Enter'&&keyPressed){keyPressed=false;pressed=false;motion();}};const blur=()=>{if(keyPressed){keyPressed=false;pressed=false;motion();}};
 const listeners:[EventTarget,string,EventListener][]=[[host,'keydown',keydown],[host,'keyup',keyup],[host,'blur',blur],[host,'click',click],[host,'pointerenter',enter],[host,'pointerleave',leave],[host,'pointerdown',down],[host,'pointercancel',up]];if(typeof document!=='undefined')listeners.push([document,'pointerup',up]);for(const[target,name,listener]of listeners)target.addEventListener(name,listener,true);
 inject(DestroyRef).onDestroy(()=>{if(timeout)clearTimeout(timeout);animation?.cancel();for(const[target,name,listener]of listeners)target.removeEventListener(name,listener,true);for(const[ctx,timer]of audio){clearTimeout(timer);close(ctx);}audio.clear();});
}
