import {test,expect,type Page,type Locator} from '@playwright/test';
async function consumer(page:Page,framework:string,theme='light',motion:'reduce'|'no-preference'='no-preference'){
 await page.emulateMedia({reducedMotion:motion});await page.route('**/neon-contract.html*',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><script type="module">import RefreshRuntime from "/@react-refresh";RefreshRuntime.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>type=>type;window.__vite_plugin_react_preamble_installed__=true;</script><script type="module" src="/e2e/fixtures/neon-edge-button-contract.tsx"></script></body></html>'}));await page.goto(`/neon-contract.html?framework=${framework}&theme=${theme}`);await page.waitForFunction(()=>typeof (window as unknown as {setNeonOptions:unknown}).setNeonOptions==='function');await expect(page.locator('#action')).toBeVisible();
}
async function update(page:Page,options:Record<string,unknown>){await page.evaluate(options=>(window as unknown as {setNeonOptions:(options:unknown)=>void}).setNeonOptions(options),options);await page.waitForTimeout(30);}
async function metrics(root:Locator){return root.evaluate(el=>[el,...el.querySelectorAll('span,svg,path')].map(node=>{const s=getComputedStyle(node);return{tag:node.tagName,text:node.tagName==='SPAN'?node.textContent:null,width:parseFloat(s.width),height:parseFloat(s.height),minHeight:s.minHeight,padding:s.padding,gap:s.columnGap,position:s.position,inset:s.inset,border:s.borderWidth,radius:s.borderRadius,background:s.backgroundColor,image:s.backgroundImage,color:s.color,font:s.fontFamily,fontSize:s.fontSize,fontWeight:s.fontWeight,lineHeight:s.lineHeight,letterSpacing:s.letterSpacing,opacity:s.opacity,cursor:s.cursor,shadow:s.boxShadow.replace(/rgba\(0, 0, 0, 0\) 0px 0px 0px 0px(?:, )?/g,'')||'none',duration:s.animationDuration,animation:s.animationName==='none'?'none':'rotate',timing:s.animationTimingFunction,pointerEvents:s.pointerEvents,outline:s.outlineStyle==='none'?'none':s.outline,outlineOffset:s.outlineOffset,ariaHidden:node.getAttribute('aria-hidden'),path:node.getAttribute('d')};}));}
for(const theme of ['light','dark'])for(const motion of ['no-preference','reduce'] as const)test(`neon default/custom, speed and glow match in ${theme} with ${motion}`,async({page})=>{
 const cases=[{}, {speed:.5,glow:false,custom:true},{speed:2},{glow:false,disabled:true},{className:'h-12 px-0 rounded-none'}];const results:Awaited<ReturnType<typeof metrics>>[]=[];for(const framework of ['react','angular']){await consumer(page,framework,theme,motion);for(const [index,options] of cases.entries()){await update(page,options);await expect(page.locator('#action')).toHaveAttribute('aria-label','Action');const actual=await metrics(page.locator('#action'));if(framework==='react')results.push(actual);else expect(actual).toEqual(results[index]);}}
});
for(const framework of ['react','angular'])test(`${framework} neon native forms, keyboard, hover and active feedback`,async({page})=>{
 await consumer(page,framework);const button=page.locator('#action');await button.focus();await page.keyboard.press('Enter');await page.keyboard.press('Space');await expect.poll(()=>page.evaluate(()=>(window as unknown as {neonEvents:string[]}).neonEvents)).toEqual(['click','click']);await update(page,{type:'submit'});await button.click();await expect.poll(()=>page.evaluate(()=>(window as unknown as {neonEvents:string[]}).neonEvents.slice(-2))).toEqual(['click','submit']);await update(page,{type:'reset'});await button.click();await expect.poll(()=>page.evaluate(()=>(window as unknown as {neonEvents:string[]}).neonEvents.at(-1))).toBe('reset');
 await update(page,{});await button.hover();const interior=button.locator('svg').locator('xpath=..');await expect(interior).toHaveCSS('background-color',test.info().project.name==='desktop'?'rgb(11, 11, 11)':'rgb(5, 5, 5)');await expect(button.locator('svg')).toHaveCSS('scale',test.info().project.name==='desktop'?'1.1':'none');await page.mouse.down();await expect(button).toHaveCSS('scale','0.98');await page.mouse.up();await page.locator('form').evaluate(el=>el.classList.add('group'));await page.locator('form').hover({position:{x:250,y:22}});await expect(interior).toHaveCSS('background-color',test.info().project.name==='desktop'?'rgb(11, 11, 11)':'rgb(5, 5, 5)');await update(page,{disabled:true});await expect(button).toBeDisabled();
 if(framework==='angular'){const states=await button.evaluate(el=>{const animations=el.getAnimations({subtree:true});(window as unknown as {destroyNeon:()=>void}).destroyNeon();return animations.map(a=>a.playState);});expect(states.every(state=>state==='idle')).toBe(true);}
});
for(const framework of ['react','angular'])test(`${framework} neon showcase`,async({page},info)=>{await page.goto(`/components/neon-edge-button?framework=${framework}`);const scope=framework==='react'?page:page.frameLocator('iframe');const button=scope.getByRole('button',{name:'Deploy preview',exact:true});await expect(button).toBeVisible();await page.addStyleTag({content:'header.sticky{opacity:0!important}.fixed{display:none!important}'});await button.screenshot({path:info.outputPath(`${framework}-neon.png`),animations:'disabled'});});
for(const theme of ['light','dark'])test(`neon website geometry and styles match in ${theme}`,async({page})=>{await page.addInitScript(value=>localStorage.setItem('kit-ui-theme',value),theme);let react:Awaited<ReturnType<typeof metrics>>|undefined;for(const framework of ['react','angular']){await page.goto(`/components/neon-edge-button?framework=${framework}`);const scope=framework==='react'?page:page.frameLocator('iframe');const button=scope.getByRole('button',{name:'Deploy preview',exact:true});await expect(button).toBeVisible();const actual=await metrics(button);if(framework==='react')react=actual;else expect(actual).toEqual(react);}});
