import {test,expect,type Page,type Locator} from '@playwright/test';
async function consumer(page:Page,framework:string,theme:string,motion:'reduce'|'no-preference'){
 await page.emulateMedia({reducedMotion:motion});await page.route('**/orbital-contract.html*',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><script type="module">import RefreshRuntime from "/@react-refresh";RefreshRuntime.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>type=>type;window.__vite_plugin_react_preamble_installed__=true;</script><script type="module" src="/e2e/fixtures/orbital-contract.tsx"></script></body></html>'}));await page.goto(`/orbital-contract.html?framework=${framework}&theme=${theme}`);await page.waitForFunction(()=>typeof (window as unknown as {setOrbitalOptions:unknown}).setOrbitalOptions==='function');await expect(page.locator('.consumer-orbital')).toBeVisible();
}
async function update(page:Page,options:Record<string,unknown>){await page.evaluate(options=>(window as unknown as {setOrbitalOptions:(options:unknown)=>void}).setOrbitalOptions(options),options);await page.waitForTimeout(30);}
async function metrics(root:Locator){return root.evaluate(el=>{for(const animation of el.getAnimations({subtree:true})){animation.pause();animation.currentTime=0;}return{role:el.getAttribute('role'),label:el.getAttribute('aria-label'),busy:el.getAttribute('aria-busy'),nodes:[el,...el.querySelectorAll('div,span,svg,circle')].map(node=>{const s=getComputedStyle(node);return{tag:node===el?'ROOT':node.tagName,width:s.width,height:s.height,position:s.position,inset:s.inset,translate:s.translate,gap:s.columnGap,radius:s.borderRadius,padding:s.padding,margin:s.margin,background:s.backgroundColor,color:s.color,font:s.fontFamily,fontSize:s.fontSize,fontWeight:s.fontWeight,lineHeight:s.lineHeight,letterSpacing:s.letterSpacing,opacity:s.opacity,transform:s.transform,pointerEvents:s.pointerEvents,clip:s.clip,clipPath:s.clipPath,whiteSpace:s.whiteSpace,overflow:s.overflow,shadow:s.boxShadow.replace(/rgba\(0, 0, 0, 0\) 0px 0px 0px 0px(?:, )?/g,'')||'none',ariaHidden:node.getAttribute('aria-hidden'),text:node.tagName==='SPAN'?node.textContent:null,stroke:node.getAttribute('stroke'),strokeWidth:node.getAttribute('stroke-width'),dash:node.getAttribute('stroke-dasharray'),circle:node.tagName==='circle'?[node.getAttribute('cx'),node.getAttribute('cy'),node.getAttribute('r')]:null};}),animations:el.getAnimations({subtree:true}).map(animation=>({duration:animation.effect!.getTiming().duration,iterations:animation.effect!.getTiming().iterations,easing:animation.effect!.getTiming().easing,frames:(animation.effect as KeyframeEffect).getKeyframes().map(frame=>({offset:frame.offset,easing:frame.easing,transform:frame.transform,opacity:frame.opacity}))}))};});}
for(const theme of ['light','dark'])for(const motion of ['no-preference','reduce'] as const)test(`orbital variants, size/speed, labels and styles match in ${theme} with ${motion}`,async({page})=>{
 const cases=[{},...['default','dense','minimal'].flatMap(variant=>[{variant,size:48,speed:.5},{variant,size:96,speed:2}]),{label:'',size:24},{label:'Reading',ariaOverride:true,ariaLabel:'Custom name',widthOverride:144},{ariaOverride:true},{className:'text-red-500'}];const results:Awaited<ReturnType<typeof metrics>>[]=[];for(const framework of ['react','angular']){await consumer(page,framework,theme,motion);for(const [index,options] of cases.entries()){await update(page,options);const actual=await metrics(page.locator('.consumer-orbital'));if(framework==='react')results.push(actual);else expect(actual).toEqual(results[index]);}}
});
for(const framework of ['react','angular'])test(`${framework} orbital showcase`,async({page},info)=>{await page.goto(`/components/orbital-loading-ring?framework=${framework}`);const scope=framework==='react'?page:page.frameLocator('iframe');const root=scope.getByRole('status',{name:'Syncing registry',exact:true});await expect(root).toBeVisible();await expect(root).toHaveCSS('width','96px');await expect(scope.getByText('Layered orbital loading with reduced-motion fallback.',{exact:true})).toBeVisible();await page.addStyleTag({content:'header.sticky{opacity:0!important}.fixed{display:none!important}'});await root.locator('xpath=..').screenshot({path:info.outputPath(`${framework}-orbital.png`),animations:'disabled'});});
for(const theme of ['light','dark'])test(`orbital website geometry and styles match in ${theme}`,async({page})=>{await page.addInitScript(value=>localStorage.setItem('kittu-ui-theme',value),theme);let react:Awaited<ReturnType<typeof metrics>>|undefined;for(const framework of ['react','angular']){await page.goto(`/components/orbital-loading-ring?framework=${framework}`);const scope=framework==='react'?page:page.frameLocator('iframe');const root=scope.getByRole('status',{name:'Syncing registry',exact:true});await expect(root).toBeVisible();const actual=await metrics(root);if(framework==='react')react=actual;else expect(actual).toEqual(react);}});
test('native orbital CSS animations stop on disposal',async({page})=>{await consumer(page,'angular','dark','no-preference');const root=page.locator('.consumer-orbital');const states=await root.evaluate(el=>{const animations=el.getAnimations({subtree:true});(window as unknown as {destroyOrbital:()=>void}).destroyOrbital();return animations.map(a=>a.playState);});expect(states).toEqual(['idle','idle','idle']);});
for(const theme of ['light','dark'])test(`orbital showcase caption and layout match in ${theme}`,async({page})=>{await page.addInitScript(value=>localStorage.setItem('kittu-ui-theme',value),theme);const results:Record<string,unknown>={};for(const framework of ['react','angular']){await page.goto(`/components/orbital-loading-ring?framework=${framework}`);const scope=framework==='react'?page:page.frameLocator('iframe');const root=scope.getByRole('status',{name:'Syncing registry',exact:true});await expect(root).toBeVisible();results[framework]=await root.locator('xpath=..').evaluate(el=>[el,...el.querySelectorAll('p')].map(node=>{const s=getComputedStyle(node),r=node.getBoundingClientRect();return{width:r.width,height:r.height,padding:s.padding,gap:s.gap,margin:node.tagName==='P'?s.margin:null,font:s.fontFamily,fontSize:s.fontSize,lineHeight:s.lineHeight,fontWeight:s.fontWeight,letterSpacing:s.letterSpacing,color:s.color,text:node.tagName==='P'?node.textContent:null};}));}expect(results.angular).toEqual(results.react);});
