import {test,expect,type Page} from '@playwright/test';
const options=async(page:Page,value:Record<string,unknown>)=>{await page.evaluate(o=>(window as any).setRainbowOptions(o),value);await page.waitForTimeout(280);};
const appearance=async(page:Page)=>page.locator('.kit-ui-rainbow-active').evaluate(el=>{const s=getComputedStyle(el),p=getComputedStyle(el,'::before'),r=el.getBoundingClientRect();const keys=['height','width','display','paddingTop','paddingBottom','paddingLeft','paddingRight','borderTopWidth','borderTopColor','borderBottomColor','borderRadius','color','fontSize','fontWeight','lineHeight','gap','backgroundImage','backgroundSize','backgroundClip','backgroundOrigin','boxShadow','opacity','transitionDuration','animationName','animationDuration','animationTimingFunction','aspectRatio','animationIterationCount'];return{styles:Object.fromEntries(keys.map(k=>[k,(s as any)[k]])),glow:Object.fromEntries(['content','opacity','filter','height','width','bottom','left','animationName','animationDuration'].map(k=>[k,(p as any)[k]])),width:r.width,height:r.height,icon:el.querySelector('svg')?getComputedStyle(el.querySelector('svg')!).width:null};});
for(const theme of ['light','dark'])for(const motion of ['reduce','no-preference'] as const)test(`rainbow variants, sizes, colors, glow and motion match ${theme} ${motion}`,async({page,context})=>{
 const react=await context.newPage();await Promise.all([page.emulateMedia({reducedMotion:motion}),react.emulateMedia({reducedMotion:motion})]);await Promise.all([page.goto(`/e2e/fixtures/rainbow-contract.html?framework=angular&theme=${theme}`),react.goto(`/e2e/fixtures/rainbow-contract.html?framework=react&theme=${theme}`)]);await expect(page.locator('#action')).toBeVisible();await expect(react.locator('#action')).toBeVisible();
 for(const variant of ['default','outline'])for(const size of ['default','sm','lg','icon']){const value={variant,size};await Promise.all([options(page,value),options(react,value)]);expect(await appearance(page)).toEqual(await appearance(react));}
 for(const value of [{glow:false,speed:6},{color1:'red',color2:'blue',color3:'green',color4:'purple',color5:'orange',speed:.5},{disabled:true},{style:{'--color-1':'pink','--rainbow-speed':'8s',width:190,opacity:.7,aspectRatio:2,animationIterationCount:3},className:'consumer-rainbow'}]){await Promise.all([options(page,value),options(react,value)]);expect(await appearance(page)).toEqual(await appearance(react));}
 await react.close();
});
for(const framework of ['react','angular'])test(`${framework} rainbow native forms, keyboard, composition and updates`,async({page})=>{
 await page.goto(`/e2e/fixtures/rainbow-contract.html?framework=${framework}`);await expect(page.locator('#action')).toBeVisible();await page.locator('#action').click();expect(await page.evaluate(()=>(window as any).rainbowEvents)).toEqual(['click','submit']);await options(page,{type:'reset'});await page.locator('#action').click();expect(await page.evaluate(()=>(window as any).rainbowEvents)).toEqual(['click','submit','click','reset']);await options(page,{disabled:true});await expect(page.locator('#action')).toBeDisabled();await options(page,{type:'button'});await page.locator('#action').focus();await page.keyboard.press('Enter');await page.keyboard.press('Space');expect(await page.evaluate(()=>(window as any).rainbowEvents.slice(-2))).toEqual(['click','click']);
 for(const mode of ['link','child']){await options(page,{mode});await expect(page.locator('#action')).toBeVisible();await expect(page.locator('#action')).toHaveAttribute('data-slot','button');await expect(page.locator('#action')).toHaveClass(/kit-ui-rainbow-active/);await page.locator('#action').click();}
 if(framework==='angular'){await options(page,{mode:'custom',size:'lg'});await expect(page.locator('kit-rainbow-button button')).toBeVisible();await expect(page.locator('kit-rainbow-button button')).toHaveCSS('height','48px');}
 await page.evaluate(()=>(window as any).destroyRainbow());await expect(page.locator('.kit-ui-rainbow-active')).toHaveCount(0);
});
for(const theme of ['light','dark'])test(`rainbow hover, focus and press match ${theme}`,async({page,context})=>{
 const react=await context.newPage();await Promise.all([page.goto(`/e2e/fixtures/rainbow-contract.html?framework=angular&theme=${theme}`),react.goto(`/e2e/fixtures/rainbow-contract.html?framework=react&theme=${theme}`)]);await expect(page.locator('#action')).toBeVisible();await expect(react.locator('#action')).toBeVisible();await Promise.all([page.locator('#action').hover(),react.locator('#action').hover()]);await Promise.all([page.waitForTimeout(400),react.waitForTimeout(400)]);expect(await appearance(page)).toEqual(await appearance(react));await Promise.all([page.mouse.move(500,500),react.mouse.move(500,500)]);await Promise.all([page.keyboard.press('Tab'),react.keyboard.press('Tab')]);await Promise.all([page.waitForTimeout(400),react.waitForTimeout(400)]);expect(await appearance(page)).toEqual(await appearance(react));await Promise.all([page.locator('#action').hover(),react.locator('#action').hover()]);await Promise.all([page.mouse.down(),react.mouse.down()]);await Promise.all([page.waitForTimeout(400),react.waitForTimeout(400)]);expect(await page.locator('#action').evaluate(el=>getComputedStyle(el).scale)).toEqual(await react.locator('#action').evaluate(el=>getComputedStyle(el).scale));await Promise.all([page.mouse.up(),react.mouse.up()]);await react.close();
});
for(const theme of ['light','dark'])test(`rainbow website demo matches ${theme}`,async({page,context},info)=>{
 const react=await context.newPage();await Promise.all([page.addInitScript(t=>localStorage.setItem('kit-ui-theme',t),theme),react.addInitScript(t=>localStorage.setItem('kit-ui-theme',t),theme)]);await Promise.all([page.goto(`/components/rainbow-button?framework=angular&theme=${theme}`),react.goto(`/components/rainbow-button?framework=react&theme=${theme}`)]);const frame=page.frameLocator('iframe');const a=frame.getByRole('button',{name:'Get Unlimited Access',exact:true});const r=react.getByRole('button',{name:'Get Unlimited Access',exact:true});await expect(a).toBeVisible();await expect(r).toBeVisible();
 await Promise.all([page.evaluate(()=>document.fonts.ready),react.evaluate(()=>document.fonts.ready),a.evaluate(()=>document.fonts.ready)]);const dimensions=(el:HTMLElement)=>{const s=getComputedStyle(el);return{width:el.getBoundingClientRect().width,height:el.getBoundingClientRect().height,font:s.fontFamily,fontSize:s.fontSize,weight:s.fontWeight,lineHeight:s.lineHeight,padding:s.padding,radius:s.borderRadius,background:s.backgroundImage,color:s.color};};expect(await a.evaluate(dimensions)).toEqual(await r.evaluate(dimensions));await Promise.all([frame.getByRole('button',{name:'outline',exact:true}).click(),react.getByRole('button',{name:'outline',exact:true}).click()]);await Promise.all([frame.getByRole('button',{name:'lg',exact:true}).click(),react.getByRole('button',{name:'lg',exact:true}).click()]);await Promise.all([frame.getByLabel('Ambient Glow').uncheck(),react.getByLabel('Ambient Glow').uncheck()]);await expect(a).toHaveCSS('height','48px');await expect(a).not.toHaveClass(/kit-ui-rainbow-glow/);await Promise.all([a.click(),r.click()]);await expect(frame.getByText('Clicked 1 time',{exact:true})).toBeVisible();await expect(frame.getByRole('checkbox')).not.toBeChecked();await expect(react.getByText('Clicked 1 time',{exact:true})).toBeVisible();await Promise.all([page.waitForTimeout(300),react.waitForTimeout(300)]);expect(await a.evaluate(dimensions)).toEqual(await r.evaluate(dimensions));await page.screenshot({path:`docs/parity/screenshots/rainbow-button-angular-${info.project.name}-${theme}.png`,fullPage:false});await react.screenshot({path:`docs/parity/screenshots/rainbow-button-react-${info.project.name}-${theme}.png`,fullPage:false});await react.close();
});
