import {test,expect,type Page,type Locator} from '@playwright/test';
async function consumer(page:Page,framework:string,theme='dark',motion:'reduce'|'no-preference'='no-preference'){
 await page.emulateMedia({reducedMotion:motion});await page.route('**/spotlight-contract.html*',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><script type="module">import RefreshRuntime from "/@react-refresh";RefreshRuntime.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>type=>type;window.__vite_plugin_react_preamble_installed__=true;</script><script type="module" src="/e2e/fixtures/spotlight-contract.tsx"></script></body></html>'}));await page.goto(`/spotlight-contract.html?framework=${framework}&theme=${theme}`);await page.waitForFunction(()=>typeof (window as unknown as {setSpotlightOptions:unknown}).setSpotlightOptions==='function');await expect(page.locator('.consumer-card')).toBeVisible();
}
async function update(page:Page,options:Record<string,unknown>){await page.evaluate(options=>(window as unknown as {setSpotlightOptions:(options:unknown)=>void;events:string[]}).setSpotlightOptions(options),options);await page.evaluate(()=>(window as unknown as {events:string[]}).events=[]);await page.waitForTimeout(350);}
async function metrics(root:Locator){return root.evaluate(el=>[el,...el.querySelectorAll('div,p,button,h4,span')].map(node=>{const s=getComputedStyle(node);return{tag:node===el?'ROOT':node.tagName,width:s.width,height:s.height,position:s.position,inset:s.inset,radius:s.borderRadius,padding:s.padding,margin:s.margin,background:s.backgroundImage,backgroundColor:s.backgroundColor,color:s.color,font:s.fontFamily,fontSize:s.fontSize,fontWeight:s.fontWeight,lineHeight:s.lineHeight,letterSpacing:s.letterSpacing,opacity:s.opacity,overflow:s.overflow,pointerEvents:s.pointerEvents,z:s.zIndex,border:s.borderWidth==='0px'?'0px':s.border,transition:s.transitionProperty,duration:s.transitionDuration,easing:s.transitionTimingFunction,text:['P','BUTTON','H4'].includes(node.tagName)?node.textContent:null};}));}
async function pointer(page:Page,root:Locator,x:number,y:number){const r=(await root.boundingBox())!;await page.mouse.move(r.x+x,r.y+y);await page.waitForTimeout(350);}
for(const theme of ['light','dark'])for(const motion of ['no-preference','reduce'] as const)test(`spotlight defaults, customization and pointer lifecycle match in ${theme} ${motion}`,async({page})=>{
 const results:unknown[]=[];const cases=[{}, {spotlightColor:'rgba(255, 100, 40, .2)',spotlightSize:180},{spotlightSize:500,className:'p-4 rounded-none'},{spotlightColor:'transparent',spotlightSize:0},{style:{width:200,color:'red',padding:8}}];for(const framework of ['react','angular']){await consumer(page,framework,theme,motion);for(const[index,options]of cases.entries()){await page.mouse.move(0,0);await update(page,options);const root=page.locator('.consumer-card');const states=[await metrics(root)];await pointer(page,root,80,50);states.push(await metrics(root));await pointer(page,root,150,70);states.push(await metrics(root));await page.mouse.move(0,0);await page.waitForTimeout(350);states.push(await metrics(root));if(framework==='react')results.push(states);else expect(states).toEqual(results[index]);}}
});
for(const override of ['move','leave','both'])for(const handler of [true,false])test(`spotlight ${override} override ${handler?'callback':'undefined'} matches React spread precedence`,async({page})=>{const results:unknown[]=[];for(const framework of ['react','angular']){await consumer(page,framework);await update(page,{moveOverride:override!=='leave',leaveOverride:override!=='move',handler});const root=page.locator('.consumer-card');await pointer(page,root,60,40);const background=await root.locator(':scope > div').nth(1).evaluate(el=>getComputedStyle(el).backgroundImage);await page.mouse.move(0,0);await page.waitForTimeout(350);const result={background,after:await root.locator(':scope > div').nth(1).evaluate(el=>getComputedStyle(el).backgroundImage),events:await page.evaluate(()=>(window as unknown as {events:string[]}).events)};if(framework==='react')results.push(result);else expect(result).toEqual(results[0]);}});
test('projected button remains keyboard accessible and native attrs survive',async({page})=>{await consumer(page,'angular');const root=page.locator('.consumer-card');await expect(root).toHaveAttribute('aria-label','Card');await expect(root).toHaveAttribute('data-consumer','spotlight');await root.focus();await page.keyboard.press('Tab');await expect(root.getByRole('button',{name:'Inspect details'})).toBeFocused();await page.keyboard.press('Enter');expect(await page.evaluate(()=>(window as unknown as {events:string[]}).events)).toEqual(['click']);});
test('ancestor group hover preserves source layer behavior',async({page})=>{let reference:unknown;for(const framework of ['react','angular']){await consumer(page,framework);await update(page,{ancestorGroup:true});const frame=page.locator('.consumer-frame'),r=(await frame.boundingBox())!;await page.mouse.move(r.x+2,r.y+2);await page.waitForTimeout(350);const actual=await metrics(page.locator('.consumer-card'));if(framework==='react')reference=actual;else expect(actual).toEqual(reference);}});
test('native spotlight disposed host no longer responds to mouse events',async({page})=>{await consumer(page,'angular');expect(await page.locator('.consumer-card').evaluate(async el=>{const layer=el.children[1] as HTMLElement;const before=layer.style.background;(window as unknown as {destroySpotlight:()=>void}).destroySpotlight();el.dispatchEvent(new MouseEvent('mousemove',{clientX:100,clientY:100,bubbles:true}));await new Promise(resolve=>setTimeout(resolve,30));return{connected:el.isConnected,unchanged:layer.style.background===before};})).toEqual({connected:false,unchanged:true});});
for(const theme of ['light','dark'])test(`spotlight website content and geometry match in ${theme}`,async({page})=>{await page.addInitScript(value=>localStorage.setItem('kittu-ui-theme',value),theme);let reference:unknown;for(const framework of ['react','angular']){await page.goto(`/components/spotlight-card?framework=${framework}`);const scope=framework==='react'?page:page.frameLocator('iframe');const heading=scope.getByRole('heading',{name:'Spotlight Shader'});await expect(heading).toBeVisible();const root=framework==='react'?heading.locator('xpath=../../..'):scope.locator('kittu-spotlight-card');const actual=await metrics(root);if(framework==='react')reference=actual;else expect(actual).toEqual(reference);}});
for(const framework of ['react','angular'])test(`${framework} spotlight showcase screenshot`,async({page},info)=>{await page.goto(`/components/spotlight-card?framework=${framework}`);const scope=framework==='react'?page:page.frameLocator('iframe');const heading=scope.getByRole('heading',{name:'Spotlight Shader'});await expect(heading).toBeVisible();const root=framework==='react'?heading.locator('xpath=../../..'):scope.locator('kittu-spotlight-card');await page.addStyleTag({content:'header.sticky{opacity:0!important}.fixed{display:none!important}'});await root.screenshot({path:info.outputPath(`${framework}-spotlight.png`),animations:'disabled'});if(info.project.name==='desktop'){await root.hover({position:{x:100,y:70}});await page.waitForTimeout(350);await root.screenshot({path:info.outputPath(`${framework}-spotlight-hover.png`),animations:'disabled'});}});
