// Keep aligned with the React Component Registry showcase.
export interface ComponentRecord {
  id: string;
  name: string;
  category: 'Motion' | 'AI' | 'Interactive' | 'Form' | 'Layout';
  status: 'Stable' | 'New' | 'Beta';
  downloads: string;
  bundleSize: string;
  rating: number;
  author: string;
  dependencies: string[];
}

export const SAMPLE_COMPONENTS_DATA: ComponentRecord[] = [
  {
    id: 'comp_01',
    name: 'AI Response',
    category: 'AI',
    status: 'New',
    downloads: '14,280',
    bundleSize: '3.4 KB',
    rating: 4.9,
    author: 'Kit UI Core',
    dependencies: ['framer-motion', 'lucide-react'],
  },
  {
    id: 'comp_02',
    name: 'Advanced Data Table',
    category: 'Interactive',
    status: 'New',
    downloads: '18,920',
    bundleSize: '4.8 KB',
    rating: 5.0,
    author: 'Kit UI Core',
    dependencies: ['framer-motion', 'lucide-react'],
  },
  {
    id: 'comp_03',
    name: 'Chat',
    category: 'AI',
    status: 'New',
    downloads: '12,450',
    bundleSize: '4.1 KB',
    rating: 4.9,
    author: 'Kit UI Core',
    dependencies: ['framer-motion', 'lucide-react'],
  },
  {
    id: 'comp_04',
    name: 'AI Agent Activity',
    category: 'AI',
    status: 'New',
    downloads: '9,830',
    bundleSize: '3.1 KB',
    rating: 4.8,
    author: 'Kit UI Core',
    dependencies: ['framer-motion', 'lucide-react'],
  },
  {
    id: 'comp_05',
    name: 'Magnetic Button',
    category: 'Motion',
    status: 'Stable',
    downloads: '42,100',
    bundleSize: '1.8 KB',
    rating: 4.9,
    author: 'Design Systems Lab',
    dependencies: ['framer-motion'],
  },
  {
    id: 'comp_06',
    name: 'Spotlight Card',
    category: 'Motion',
    status: 'Stable',
    downloads: '38,400',
    bundleSize: '1.5 KB',
    rating: 4.8,
    author: 'Design Systems Lab',
    dependencies: ['framer-motion'],
  },
  {
    id: 'comp_07',
    name: 'Morphing Dialog',
    category: 'Interactive',
    status: 'Stable',
    downloads: '29,300',
    bundleSize: '2.6 KB',
    rating: 4.9,
    author: 'Kit UI Core',
    dependencies: ['framer-motion', 'lucide-react'],
  },
  {
    id: 'comp_08',
    name: 'Interactive Timeline',
    category: 'Interactive',
    status: 'Stable',
    downloads: '24,100',
    bundleSize: '3.8 KB',
    rating: 4.7,
    author: 'DevOps Tooling',
    dependencies: ['framer-motion', 'lucide-react'],
  },
  {
    id: 'comp_09',
    name: 'Animated Tabs',
    category: 'Layout',
    status: 'Stable',
    downloads: '51,200',
    bundleSize: '1.4 KB',
    rating: 5.0,
    author: 'Kit UI Core',
    dependencies: ['framer-motion'],
  },
  {
    id: 'comp_10',
    name: 'Notification Stack',
    category: 'Interactive',
    status: 'Stable',
    downloads: '31,800',
    bundleSize: '2.9 KB',
    rating: 4.8,
    author: 'Design Systems Lab',
    dependencies: ['framer-motion', 'lucide-react'],
  },
  {
    id: 'comp_11',
    name: 'Floating Action Dock',
    category: 'Layout',
    status: 'Stable',
    downloads: '22,400',
    bundleSize: '2.2 KB',
    rating: 4.7,
    author: 'Apple HIG Concepts',
    dependencies: ['framer-motion'],
  },
  {
    id: 'comp_12',
    name: 'Origin Dropdown',
    category: 'Form',
    status: 'Beta',
    downloads: '16,700',
    bundleSize: '2.5 KB',
    rating: 4.6,
    author: 'Form Primitives',
    dependencies: ['framer-motion', 'lucide-react'],
  },
];

