import React from 'react';
import { GitPullRequest, Sparkles, CheckCircle2 } from 'lucide-react';
import { DocCodeBlock } from '../DocCodeBlock';
import { DocPagination } from '../DocPagination';

export interface DocCollaborationProps {
  onNavigateSection: (sectionId: string) => void;
}

export const DocCollaboration: React.FC<DocCollaborationProps> = ({ onNavigateSection }) => {
  return (
    <article className="space-y-14 animate-fade-in text-text-secondary">
      {/* Header */}
      <header className="space-y-4 border-b border-border pb-10">
        <span className="text-[11px] font-mono text-text-muted uppercase tracking-[0.18em]">
          Architecture &amp; Engine · 03
        </span>
        <h1 className="text-3xl sm:text-[40px] font-semibold tracking-[-0.02em] text-text-primary leading-[1.1]">
          Contributing Guide
        </h1>
        <p className="text-[15px] text-text-secondary leading-relaxed max-w-2xl">
          Learn how to add new components and contribute to Kit UI. Because of our automated single source of truth engine, adding a component takes just two files and a few minutes.
        </p>
      </header>

      {/* The 2-File Rule */}
      <section className="p-5 rounded-lg border border-border bg-surface space-y-3">
        <div className="flex items-center gap-2 text-[14px] text-text-primary font-semibold">
          <Sparkles className="w-3.5 h-3.5 text-text-primary" />
          <span>The Two-File Contribution Rule</span>
        </div>
        <p className="text-[13px] text-text-secondary leading-relaxed">
          When adding a component, you only ever create or touch two files in{' '}
          <code className="text-text-primary font-mono bg-surface-raised border border-border px-1.5 py-0.5 rounded text-[12px]">
            src/components/ui/
          </code>
          :
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-1">
          <div className="p-3.5 rounded-md border border-border bg-surface-raised text-[12.5px]">
            <span className="text-[13px] text-text-primary font-semibold block mb-1">
              1. Component (.tsx)
            </span>
            <span className="text-text-muted">React + Tailwind CSS + Framer Motion implementation.</span>
          </div>
          <div className="p-3.5 rounded-md border border-border bg-surface-raised text-[12.5px]">
            <span className="text-[13px] text-text-primary font-semibold block mb-1">
              2. Metadata (.meta.ts)
            </span>
            <span className="text-text-muted">Name, description, props documentation, and usage code.</span>
          </div>
        </div>
        <p className="text-[12px] text-text-muted">
          All JSON endpoints, registry files, and website documentation pages are automatically generated by the engine.
        </p>
      </section>

      {/* Step 1: Scaffold */}
      <section className="space-y-4">
        <span className="font-mono text-[11px] tracking-[0.18em] text-text-muted uppercase">
          Step 01
        </span>
        <h2 className="text-[16px] font-semibold text-text-primary tracking-[-0.01em]">
          Scaffold a Starter Template
        </h2>
        <p className="text-[14px] text-text-secondary leading-relaxed">
          Use the built-in scaffolding command to generate starter boilerplate:
        </p>
        <DocCodeBlock code="npm run component:new TiltCard" language="bash" isTerminal={true} />
        <p className="text-[12px] text-text-muted">
          This creates{' '}
          <code className="text-text-primary font-mono text-[12px]">src/components/ui/TiltCard.tsx</code> and{' '}
          <code className="text-text-primary font-mono text-[12px]">src/components/ui/TiltCard.meta.ts</code>.
        </p>
      </section>

      {/* Step 2: Implement Component */}
      <section className="space-y-4">
        <span className="font-mono text-[11px] tracking-[0.18em] text-text-muted uppercase">
          Step 02
        </span>
        <h2 className="text-[16px] font-semibold text-text-primary tracking-[-0.01em]">
          Write the Component Code
        </h2>
        <p className="text-[14px] text-text-secondary leading-relaxed">
          Write your React component using Framer Motion spring physics and clean Tailwind CSS styling:
        </p>

        <DocCodeBlock
          code={`import React, { useRef } from 'react';
import { motion, useSpring } from 'framer-motion';
import { cn } from '../../lib/utils';

export interface TiltCardProps extends React.HTMLAttributes<HTMLDivElement> {
  children: React.ReactNode;
  maxTilt?: number;
  className?: string;
}

export const TiltCard: React.FC<TiltCardProps> = ({
  children,
  maxTilt = 15,
  className,
  ...props
}) => {
  const rotateX = useSpring(0, { stiffness: 300, damping: 25 });
  const rotateY = useSpring(0, { stiffness: 300, damping: 25 });

  return (
    <motion.div
      style={{ rotateX, rotateY, transformStyle: 'preserve-3d' }}
      className={cn('rounded-2xl border border-[#1F1F1F] bg-[#0E0E0E] p-6', className)}
      {...(props as any)}
    >
      {children}
    </motion.div>
  );
};`}
          language="tsx"
          title="src/components/ui/TiltCard.tsx"
        />
      </section>

      {/* Step 3: Define Metadata */}
      <section className="space-y-4">
        <span className="font-mono text-[11px] tracking-[0.18em] text-text-muted uppercase">
          Step 03
        </span>
        <h2 className="text-[16px] font-semibold text-text-primary tracking-[-0.01em]">
          Define Component Metadata
        </h2>
        <p className="text-[14px] text-text-secondary leading-relaxed">
          Define props, category, badges, and usage snippet in the metadata file:
        </p>

        <DocCodeBlock
          code={`import type { KittuComponentMeta } from '../../types/component';

export const TiltCardMeta: KittuComponentMeta = {
  id: 'tilt-card',
  name: 'Tilt Card',
  category: 'Motion',
  description: 'Tactile 3D perspective tilt card that tracks pointer momentum with springs.',
  badges: ['Framer Motion', '3D Perspective'],
  cliCommand: 'npx shadcn@latest add chaitanay-kumar/kittu-ui/tilt-card',
  dependencies: ['framer-motion', 'clsx', 'tailwind-merge'],
  files: ['src/components/ui/TiltCard.tsx'],
  props: [
    { name: 'children', type: 'React.ReactNode', required: true, description: 'Inner card contents' },
    { name: 'maxTilt', type: 'number', defaultValue: '15', description: 'Max rotation angle' },
  ],
  usageExample: \`<TiltCard maxTilt={20}>
  <p className="text-white">Hover to experience 3D tilt.</p>
</TiltCard>\`,
  sourceCode: '', // Automatically populated by sync script
};`}
          language="typescript"
          title="src/components/ui/TiltCard.meta.ts"
        />
      </section>

      {/* Step 4: Sync & Verify */}
      <section className="space-y-4">
        <span className="font-mono text-[11px] tracking-[0.18em] text-text-muted uppercase">
          Step 04
        </span>
        <h2 className="text-[16px] font-semibold text-text-primary tracking-[-0.01em]">
          Sync &amp; Validate
        </h2>
        <p className="text-[14px] text-text-secondary leading-relaxed">
          Execute the sync and validation script to generate registry artifacts:
        </p>

        <DocCodeBlock
          code={`# Sync all components and metadata
npm run component:sync

# Validate all schemas and disk paths
npm run registry:validate`}
          language="bash"
          isTerminal={true}
        />
      </section>

      {/* PR Checklist */}
      <section className="p-5 rounded-lg border border-border bg-surface space-y-3">
        <div className="flex items-center gap-2">
          <GitPullRequest className="w-3.5 h-3.5 text-text-primary" />
          <h2 className="text-[14px] font-semibold text-text-primary">Pull Request Checklist</h2>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-[13px]">
          {[
            'Component is written in TypeScript (.tsx) with clean exports',
            'Corresponding .meta.ts is complete with props and usage',
            'npm run component:sync ran with 0 errors',
            'npm run registry:validate passed cleanly',
            'Spring motion feels smooth and responsive',
            'Accessible with keyboard and reduced-motion fallback',
          ].map((item, idx) => (
            <div
              key={idx}
              className="flex items-start gap-2 p-2.5 rounded-md border border-border bg-surface-raised"
            >
              <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500 dark:text-emerald-400 shrink-0 mt-0.5" />
              <span className="text-text-secondary">{item}</span>
            </div>
          ))}
        </div>
      </section>

      {/* Pagination Footer */}
      <DocPagination currentTopic="collaboration" onNavigateTopic={onNavigateSection} />
    </article>
  );
};
