export const typewriterButtonPort={
 imports:`import {ViewEncapsulation,booleanAttribute} from '@angular/core';
import {NgTemplateOutlet} from '@angular/common';
import type {TypewriterButtonVariant,TypewriterButtonCallback} from './typewriter-button-types';
import {installTypewriterButton} from './typewriter-button-controller';`,componentImports:'NgTemplateOutlet',stylesFile:'./typewriter-button.css',componentSelector:'kit-typewriter-button,button[kitTypewriterButton]',
 hostMetadata:`{'data-kit':'typewriter-button','[class]':'native ? buttonClass() : "k-typewriter-host"','[attr.type]':'native ? type() : null','[attr.disabled]':'native && disabled() ? "" : null','[attr.aria-label]':'native ? text() : null'}`,
 description:'React-matched character-by-character button with required text, typing duration, auto-start, completion callback and optional synthesized keystroke audio.',
 inputs:['text: string (required; React children)','variant: TypewriterButtonVariant','charDuration: number','autoStart: boolean','soundEnabled: boolean','soundVolume: number','onComplete: TypewriterButtonCallback','onClick: TypewriterButtonCallback','disabled: boolean','type: button | submit | reset','className: string'],outputs:[],
 template:`<ng-template #content><span class="k-typewriter-content"><span>{{displayedText()}}</span>@if(isTyping()){<span class="k-typewriter-cursor"></span>}</span></ng-template>@if(native){<ng-container [ngTemplateOutlet]="content"/>}@else{<button [class]="buttonClass()" [type]="type()" [disabled]="disabled()" [attr.aria-label]="text()"><ng-container [ngTemplateOutlet]="content"/></button>}`,
 body:`readonly native=inject<ElementRef<HTMLElement>>(ElementRef).nativeElement.tagName==='BUTTON';readonly text=input.required<string>();readonly variant=input<TypewriterButtonVariant,TypewriterButtonVariant|undefined>('primary',{transform:value=>value===undefined?'primary':value});readonly charDuration=input<number,number|undefined>(75,{transform:value=>value===undefined?75:value});readonly soundVolume=input<number,number|undefined>(.25,{transform:value=>value===undefined?.25:value});readonly autoStart=input(false,{transform:booleanAttribute});readonly soundEnabled=input(false,{transform:booleanAttribute});readonly disabled=input(false,{transform:booleanAttribute});readonly onComplete=input<TypewriterButtonCallback>();readonly onClick=input<TypewriterButtonCallback>();readonly type=input<'button'|'submit'|'reset','button'|'submit'|'reset'|undefined>('button',{transform:value=>value===undefined?'button':value});readonly className=input<string,string|undefined>('',{transform:value=>value===undefined?'':value});readonly displayedText=signal('');readonly isTyping=signal(false);readonly buttonClass=computed(()=>['k-typewriter-parity','k-typewriter-'+this.variant(),this.disabled()?'k-typewriter-disabled':'',this.className()].filter(Boolean).join(' '));constructor(){installTypewriterButton(this);}`
};
