export const advancedDataTablePort = {
  id: 'advanced-data-table',kind: 'plain' as const,typeParameters:'<T = any>',
  description: 'React-compatible native table and cards, typed columns, custom cell/detail templates, multi-value filters, current-page selection and bulk callbacks.',
  inputs: ['data: T[]','columns: ColumnDef<T>[]','getRowId: (row: T, index: number) => string','title: string','searchPlaceholder: string','defaultPageSize: number','defaultViewMode: DataTableViewMode','accentColor: string','renderSubComponent: TemplateRef<DataTableRowContext<T>>','isLoading: boolean','error: string | null','className: string','onBulkDelete: (ids: string[]) => void','onBulkExport: (ids: string[]) => void'],
  outputs: ['bulkDelete: string[]','bulkExport: string[]'],
  imports: `import { TemplateRef } from '@angular/core';
import { KitDataTableComponent,KitDataTableToolbarComponent,KitDataTableFiltersComponent,KitDataTableContentComponent,KitDataTablePaginationComponent } from './data-table-parts';
import type { ColumnDef, DataTableRowContext, DataTableViewMode } from './data-table-types';`,
  componentImports: 'KitDataTableComponent,KitDataTableToolbarComponent,KitDataTableFiltersComponent,KitDataTableContentComponent,KitDataTablePaginationComponent',
  template: `<kit-data-table [data]="data()" [columns]="columns()" [getRowId]="getRowId()" [defaultPageSize]="defaultPageSize()" [defaultViewMode]="defaultViewMode()" [accentColor]="accentColor()" [renderSubComponent]="renderSubComponent()" [isLoading]="isLoading()" [error]="error()" [className]="className()"><kit-data-table-toolbar [title]="title()" [searchPlaceholder]="searchPlaceholder()" [onBulkDelete]="onBulkDelete()" [onBulkExport]="onBulkExport()" (bulkDelete)="bulkDelete.emit($event)" (bulkExport)="bulkExport.emit($event)"/><kit-data-table-filters/><kit-data-table-content/><kit-data-table-pagination/></kit-data-table>`,
  body: `readonly data=input<T[]>([]);readonly columns=input<ColumnDef<T>[]>([]);readonly getRowId=input<(row:T,index:number)=>string>((row,index)=>(row as any).id||'row-'+index);readonly title=input('');readonly searchPlaceholder=input('Search...');readonly defaultPageSize=input(10);readonly defaultViewMode=input<DataTableViewMode>('auto');readonly accentColor=input<string>();readonly renderSubComponent=input<TemplateRef<DataTableRowContext<T>>>();readonly isLoading=input(false);readonly error=input<string|null>(null);readonly className=input('');readonly onBulkDelete=input<(ids:string[])=>void>();readonly onBulkExport=input<(ids:string[])=>void>();readonly bulkDelete=output<string[]>();readonly bulkExport=output<string[]>();`
};
