export const pressButtonPort={
 imports:`import {ViewEncapsulation,booleanAttribute} from '@angular/core';
import {NgTemplateOutlet} from '@angular/common';
import type {PressButtonVariant,PressButtonSize} from './press-button-types';
import {installPressButtonMotion} from './press-button-motion';`,componentImports:'NgTemplateOutlet',stylesFile:'./press-button.css',componentSelector:'kit-press-button,button[kitPressButton]',
 hostMetadata:`{'data-kit':'press-button','[class]':'native ? buttonClass() : "k-press-host"','[attr.type]':'native ? type() : null','[attr.disabled]':'native && disabled() ? "" : null'}`,
 description:'React-matched tactile button with four variants, four sizes, configurable layered press compression, projected content and native form semantics.',
 inputs:['variant: PressButtonVariant','size: PressButtonSize','pressStrength: number','fullWidth: boolean','disabled: boolean','type: button | submit | reset','className: string'],outputs:[],
 template:`<ng-template #content><span class="k-press-content"><ng-content/></span></ng-template>@if(native){<ng-container [ngTemplateOutlet]="content"/>}@else{<button [class]="buttonClass()" [type]="type()" [disabled]="disabled()"><ng-container [ngTemplateOutlet]="content"/></button>}`,
 body:`readonly native=inject<ElementRef<HTMLElement>>(ElementRef).nativeElement.tagName==='BUTTON';readonly variant=input<PressButtonVariant,PressButtonVariant|undefined>('primary',{transform:value=>value===undefined?'primary':value});readonly size=input<PressButtonSize,PressButtonSize|undefined>('md',{transform:value=>value===undefined?'md':value});readonly pressStrength=input<number,number|undefined>(.04,{transform:value=>value===undefined?.04:value});readonly fullWidth=input(false,{transform:booleanAttribute});readonly disabled=input(false,{transform:booleanAttribute});readonly type=input<'button'|'submit'|'reset','button'|'submit'|'reset'|undefined>('button',{transform:value=>value===undefined?'button':value});readonly className=input<string,string|undefined>('',{transform:value=>value===undefined?'':value});readonly buttonClass=computed(()=>['k-press-parity','k-press-'+this.variant(),this.variant()==='ghost'?'':'k-press-'+this.size(),this.fullWidth()?'k-press-full':'',this.disabled()?'k-press-disabled':'',this.className()].filter(Boolean).join(' '));constructor(){installPressButtonMotion(this.disabled,this.pressStrength);}`
};
