const content=`<div class="k-hamburger-icon" [style.width.px]="size()" [style.height.px]="size()">@for(line of [0,1,2];track line){<span class="k-hamburger-line" [style.width.px]="size()" [style.height.px]="stroke()" [style.background-color]="color()"></span>}</div>`;
export const hamburgerMenuPort={
 imports:`import {ViewEncapsulation,booleanAttribute} from '@angular/core';
import {NgTemplateOutlet} from '@angular/common';
import {installHamburgerMotion} from './hamburger-menu-motion';`,componentImports:'NgTemplateOutlet',stylesFile:'./hamburger-menu.css',componentSelector:'kit-hamburger-menu,button[kitHamburgerMenu]',
 hostMetadata:`{'data-kit':'hamburger-menu','[class]':'native ? buttonClass() : "k-hamburger-host"','[attr.type]':'native ? type() : null','[attr.disabled]':'native && disabled() ? "" : null','[attr.aria-label]':'native ? accessibleLabel() : null','[attr.aria-expanded]':'native ? expanded() : null','(click)':'hostClick($event)'}`,
 description:'Controlled three-line menu toggle with React-matched spring transforms, native button attributes and accessible open/close labels.',
 inputs:['isOpen: boolean (required)','size: number','color: string','label: string','disabled: boolean','type: button | submit | reset','className: string','aria-label: string | null','aria-expanded: boolean | string | null','onClick: ((event: MouseEvent) => void) | null'],outputs:['change: boolean'],
 template:`<ng-template #content>${content}</ng-template>@if(native){<ng-container [ngTemplateOutlet]="content"/>}@else{<button [class]="buttonClass()" [attr.type]="type()" [disabled]="disabled()" [attr.aria-label]="accessibleLabel()" [attr.aria-expanded]="expanded()" (click)="activate($event)"><ng-container [ngTemplateOutlet]="content"/></button>}`,
 body:`readonly native=inject<ElementRef<HTMLElement>>(ElementRef).nativeElement.tagName==='BUTTON';readonly isOpen=input.required<boolean>();readonly change=output<boolean>();readonly size=input<number,number|undefined>(24,{transform:value=>value===undefined?24:value});readonly color=input<string,string|undefined>('currentColor',{transform:value=>value===undefined?'currentColor':value});readonly label=input<string,string|undefined>('Menu',{transform:value=>value===undefined?'Menu':value});readonly disabled=input(false,{transform:booleanAttribute});readonly type=input<'button'|'submit'|'reset'|undefined>('button');readonly className=input<string,string|undefined>('',{transform:value=>value===undefined?'':value});readonly ariaLabel=input<{provided:boolean;value:string|null|undefined},string|null|undefined>({provided:false,value:undefined},{alias:'aria-label',transform:value=>({provided:true,value})});readonly ariaExpanded=input<{provided:boolean;value:boolean|string|null|undefined},boolean|string|null|undefined>({provided:false,value:undefined},{alias:'aria-expanded',transform:value=>({provided:true,value})});readonly onClick=input<((event:MouseEvent)=>void)|null|undefined>(()=>{if(!this.disabled())this.change.emit(!this.isOpen());});readonly stroke=computed(()=>Math.max(2,this.size()*.08));readonly accessibleLabel=computed(()=>this.ariaLabel().provided?this.ariaLabel().value:(this.isOpen()?'Close ':'Open ')+this.label());readonly expanded=computed(()=>this.ariaExpanded().provided?this.ariaExpanded().value:this.isOpen());readonly buttonClass=computed(()=>['k-hamburger-parity',this.className()].filter(Boolean).join(' '));hostClick(event:MouseEvent):void{if(this.native)this.activate(event);}activate(event:MouseEvent):void{this.onClick()?.(event);}constructor(){installHamburgerMotion(this.isOpen,this.size);}`
};
