export const magneticButtonPort={
 imports:`import {ViewEncapsulation,booleanAttribute} from '@angular/core';
import {NgTemplateOutlet} from '@angular/common';
import type {MagneticButtonVariant,MagneticButtonSize} from './magnetic-button-types';
import {installMagneticMotion} from './magnetic-button-motion';`,componentImports:'NgTemplateOutlet',stylesFile:'./magnetic-button.css',componentSelector:'kit-magnetic-button,button[kitMagneticButton]',
 hostMetadata:`{'data-kit':'magnetic-button','[class]':'native ? buttonClass() : "k-magnetic-host"','[attr.type]':'native ? type() : null','[attr.disabled]':'native && disabled() ? "" : null'}`,
 description:'React-matched magnetic spring button with projected content, four variants, three sizes, hover glow and native form attributes/events.',
 inputs:['strength: number','variant: primary | secondary | outline | ghost','size: sm | md | lg','glow: boolean','disabled: boolean','type: button | submit | reset','className: string'],outputs:[],
 template:`<ng-template #content>@if(glow() && hovered()){<span class="k-magnetic-glow"></span>}<span class="k-magnetic-content"><ng-content/></span></ng-template>@if(native){<ng-container [ngTemplateOutlet]="content"/>}@else{<button [class]="buttonClass()" [attr.type]="type()" [disabled]="disabled()"><ng-container [ngTemplateOutlet]="content"/></button>}`,
 body:`readonly native=inject<ElementRef<HTMLElement>>(ElementRef).nativeElement.tagName==='BUTTON';readonly hovered=signal(false);readonly strength=input<number,number|undefined>(.35,{transform:value=>value===undefined?.35:value});readonly variant=input<MagneticButtonVariant,MagneticButtonVariant|undefined>('primary',{transform:value=>value===undefined?'primary':value});readonly size=input<MagneticButtonSize,MagneticButtonSize|undefined>('md',{transform:value=>value===undefined?'md':value});readonly glow=input(true,{transform:(value:unknown)=>value===undefined?true:booleanAttribute(value)});readonly disabled=input(false,{transform:booleanAttribute});readonly type=input<'button'|'submit'|'reset'>();readonly className=input<string,string|undefined>('',{transform:value=>value===undefined?'':value});readonly buttonClass=computed(()=>['k-magnetic-parity focus-ring','k-magnetic-'+this.variant(),'k-magnetic-'+this.size(),this.className()].filter(Boolean).join(' '));constructor(){installMagneticMotion(this.strength,this.disabled,this.hovered);}`
};
