import type { KittuUIComponentMeta } from '../../types/component';

const meta: KittuUIComponentMeta = {
  title: 'AI Response',
  description: 'A production-ready, accessible AI response component supporting streaming markdown, syntax-styled code blocks, citations, feedback actions, and tool execution status.',
  category: 'Feedback',
  tagline: 'Production-ready streaming AI response with sources and actions',
  badges: ['AI', 'Streaming', 'Markdown', 'Interactive'],
  createdAt: '2026-09-21',
  features: [
    'Progressive streaming state with typing indicator and loading skeleton',
    'Rich Markdown rendering with headings, lists, blockquotes, and tables',
    'Syntax-highlighted code blocks with dedicated one-click copy buttons',
    'Composable cited sources list with expandable link pills and previews',
    'Built-in user feedback actions (Copy, Regenerate, Like, Dislike)',
    'Seamless integration with Agent Activity and tool execution traces',
    'Fully accessible keyboard navigation and ARIA live regions for streaming updates',
  ],
  props: [
    { name: 'content', type: 'string', default: "''", description: 'Markdown or plain text response generated by the AI model' },
    { name: 'status', type: "'idle' | 'generating' | 'streaming' | 'complete' | 'error' | 'cancelled'", default: "'complete'", description: 'Current generation lifecycle state' },
    { name: 'modelName', type: 'string', default: "'Kittu AI 2.0'", description: 'Model identifier badge displayed in header' },
    { name: 'sources', type: 'AIResponseSource[]', default: '[]', description: 'Array of citations or references referenced in the answer' },
    { name: 'onRegenerate', type: '() => void', default: 'undefined', description: 'Optional callback fired when the user clicks the regenerate button' },
    { name: 'onFeedback', type: "(type: 'like' | 'dislike') => void", default: 'undefined', description: 'Optional callback fired when the user provides quality feedback' },
    { name: 'children', type: 'ReactNode', default: 'undefined', description: 'Optional custom composition using AIResponse compound subcomponents' },
    { name: 'className', type: 'string', default: 'undefined', description: 'Custom Tailwind class names for styling overrides' },
  ],
  accessibility: [
    'Uses semantic role="region" with aria-live="polite" for screen-reader streaming announcements',
    'All interactive controls (Copy, Like, Dislike, Links) feature explicit focus-visible rings and ARIA labels',
    'Code blocks feature keyboard-accessible copy triggers with affirmative screen-reader labels',
    'Respects reduced motion preferences through soft, non-intrusive physics springs',
  ],
  usageCode: `import { AIResponse, AIResponseHeader, AIResponseContent, AIResponseSources, AIResponseActions } from "@/components/ui/ai-response";

export function Demo() {
  return (
    <AIResponse
      status="complete"
      modelName="Claude 3.7 Sonnet"
      content="Here is a verified solution using **Kittu UI** motion tokens:\\n\\n\`\`\`typescript\\nimport { motionTransitions } from '@/lib/motion-tokens';\\n\\nexport const config = motionTransitions.springSnappy;\\n\`\`\`"
      sources={[
        { id: 1, title: "Kittu UI Motion Tokens", url: "https://kittu-ui.pro/docs" },
        { id: 2, title: "Framer Motion Spring Spec", url: "https://www.framer.com/motion/" }
      ]}
      onRegenerate={() => console.log('Regenerating...')}
    />
  );
}`,
};

export default meta;
